-- CI-only staging baseline for historical parser regression tables that exist
-- in production but predate the migrations currently committed to this repo.
-- This file is injected only into disposable CI and is never a production migration.

create schema if not exists staging;

create table if not exists staging.parser_runs (
  id uuid primary key,
  parser_version text not null,
  source_batch text not null,
  thread_count integer not null,
  extraction_count integer not null,
  metrics jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  payload_gzip_base64 text
);

create table if not exists staging.parser_regression_results (
  id bigint generated by default as identity primary key,
  run_id uuid not null references staging.parser_runs(id) on delete cascade,
  issue_type text not null,
  v2_errors integer not null,
  v3_errors integer not null,
  passed boolean not null,
  notes text,
  created_at timestamptz not null default now()
);
