-- PA2.21 — Operational Relationship Activation.
-- Controlled, audited linking of normalized RFQ -> Offer -> Order.
-- No relationship is inferred from company name, email domain, free text, or legacy thread similarity.

create table if not exists public.commercial_relationship_activations (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  relationship_type text not null check (relationship_type in ('offer_rfq','order_offer','order_rfq')),
  source_entity_id uuid not null,
  target_entity_id uuid not null,
  evidence_type text not null check (evidence_type in ('shared_normalized_conversation_exact_product')),
  status text not null check (status in ('applied')),
  activated_by uuid not null references auth.users(id) on delete restrict,
  activated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (organization_id, relationship_type, source_entity_id, target_entity_id)
);

alter table public.commercial_relationship_activations enable row level security;

drop policy if exists "members can read commercial relationship activations"
on public.commercial_relationship_activations;
create policy "members can read commercial relationship activations"
on public.commercial_relationship_activations
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_relationship_activations from public,anon;
grant select on table public.commercial_relationship_activations to authenticated,service_role;
grant usage,select on sequence public.commercial_relationship_activations_id_seq to service_role;

create or replace function private.normalized_line_multiset_matches(
  p_organization_id uuid,
  p_left_kind text,
  p_left_id uuid,
  p_right_kind text,
  p_right_id uuid
)
returns boolean
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  left_missing int;
  right_missing int;
  mismatch_count int;
begin
  if p_left_kind not in ('rfq','offer','order') or p_right_kind not in ('rfq','offer','order') then
    return false;
  end if;

  execute format(
    'select count(*) from public.%I where organization_id=$1 and %I=$2 and canonical_product_key is null',
    case p_left_kind when 'rfq' then 'rfq_lines' when 'offer' then 'offer_lines' else 'order_lines' end,
    case p_left_kind when 'rfq' then 'rfq_id' when 'offer' then 'offer_id' else 'order_id' end
  ) into left_missing using p_organization_id,p_left_id;

  execute format(
    'select count(*) from public.%I where organization_id=$1 and %I=$2 and canonical_product_key is null',
    case p_right_kind when 'rfq' then 'rfq_lines' when 'offer' then 'offer_lines' else 'order_lines' end,
    case p_right_kind when 'rfq' then 'rfq_id' when 'offer' then 'offer_id' else 'order_id' end
  ) into right_missing using p_organization_id,p_right_id;

  if left_missing>0 or right_missing>0 then return false; end if;

  execute format(
    $q$
    with l as (
      select canonical_product_key,count(*) n
      from public.%I where organization_id=$1 and %I=$2
      group by canonical_product_key
    ),
    r as (
      select canonical_product_key,count(*) n
      from public.%I where organization_id=$1 and %I=$3
      group by canonical_product_key
    )
    select count(*) from (
      select coalesce(l.canonical_product_key,r.canonical_product_key) k,
             coalesce(l.n,0) ln,coalesce(r.n,0) rn
      from l full join r using(canonical_product_key)
      where coalesce(l.n,0)<>coalesce(r.n,0)
    ) x
    $q$,
    case p_left_kind when 'rfq' then 'rfq_lines' when 'offer' then 'offer_lines' else 'order_lines' end,
    case p_left_kind when 'rfq' then 'rfq_id' when 'offer' then 'offer_id' else 'order_id' end,
    case p_right_kind when 'rfq' then 'rfq_lines' when 'offer' then 'offer_lines' else 'order_lines' end,
    case p_right_kind when 'rfq' then 'rfq_id' when 'offer' then 'offer_id' else 'order_id' end
  ) into mismatch_count using p_organization_id,p_left_id,p_right_id;

  return mismatch_count=0;
end;
$$;

revoke all on function private.normalized_line_multiset_matches(uuid,text,uuid,text,uuid) from public,anon;
grant execute on function private.normalized_line_multiset_matches(uuid,text,uuid,text,uuid) to authenticated,service_role;

create or replace function public.p1_operational_relationship_readiness(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with offer_rfq_raw as (
      select o.id source_id,r.id target_id,o.conversation_id,
             count(*) over(partition by o.id) candidate_count
      from public.offers o
      join public.rfqs r
        on r.organization_id=o.organization_id
       and r.conversation_id=o.conversation_id
       and o.conversation_id is not null
      where o.organization_id=p_organization_id
        and o.rfq_id is null
        and private.normalized_line_multiset_matches(p_organization_id,'offer',o.id,'rfq',r.id)
    ),
    offer_rfq as (
      select 'offer_rfq'::text relationship_type,source_id,target_id,conversation_id
      from offer_rfq_raw where candidate_count=1
    ),
    order_offer_raw as (
      select o.id source_id,f.id target_id,o.conversation_id,
             count(*) over(partition by o.id) candidate_count
      from public.orders o
      join public.offers f
        on f.organization_id=o.organization_id
       and f.conversation_id=o.conversation_id
       and o.conversation_id is not null
      where o.organization_id=p_organization_id
        and o.offer_id is null
        and private.normalized_line_multiset_matches(p_organization_id,'order',o.id,'offer',f.id)
    ),
    order_offer as (
      select 'order_offer'::text relationship_type,source_id,target_id,conversation_id
      from order_offer_raw where candidate_count=1
    ),
    order_rfq_raw as (
      select o.id source_id,r.id target_id,o.conversation_id,
             count(*) over(partition by o.id) candidate_count
      from public.orders o
      join public.rfqs r
        on r.organization_id=o.organization_id
       and r.conversation_id=o.conversation_id
       and o.conversation_id is not null
      where o.organization_id=p_organization_id
        and o.rfq_id is null
        and private.normalized_line_multiset_matches(p_organization_id,'order',o.id,'rfq',r.id)
    ),
    order_rfq as (
      select 'order_rfq'::text relationship_type,source_id,target_id,conversation_id
      from order_rfq_raw where candidate_count=1
    ),
    candidates as (
      select * from offer_rfq
      union all select * from order_offer
      union all select * from order_rfq
    )
    select jsonb_build_object(
      'summary',jsonb_build_object(
        'ready_total',(select count(*) from candidates),
        'offer_rfq_ready',(select count(*) from candidates where relationship_type='offer_rfq'),
        'order_offer_ready',(select count(*) from candidates where relationship_type='order_offer'),
        'order_rfq_ready',(select count(*) from candidates where relationship_type='order_rfq')
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'relationship_type',relationship_type,
          'source_entity_id',source_id,
          'target_entity_id',target_id,
          'conversation_id',conversation_id,
          'evidence_type','shared_normalized_conversation_exact_product'
        ) order by relationship_type,source_id)
        from (select * from candidates limit greatest(1,least(coalesce(p_limit,100),500))) q
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'requires_shared_normalized_conversation',true,
        'requires_exact_product_multiset',true,
        'requires_unique_candidate',true,
        'company_inference',false,
        'email_domain_inference',false,
        'legacy_thread_similarity',false,
        'bulk_auto_activation',false
      )
    )
  );
end;
$$;

revoke all on function public.p1_operational_relationship_readiness(uuid,integer) from public,anon;
grant execute on function public.p1_operational_relationship_readiness(uuid,integer) to authenticated,service_role;

create or replace function private.activate_operational_relationship_impl(
  p_organization_id uuid,
  p_relationship_type text,
  p_source_entity_id uuid,
  p_target_entity_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  source_conversation uuid;
  target_conversation uuid;
  existing_target uuid;
  activation_id bigint;
  line_count int;
  linked_line_count int;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;
  if p_relationship_type not in ('offer_rfq','order_offer','order_rfq') then
    raise exception 'Unsupported relationship type';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'relationship:'||p_organization_id::text||':'||p_relationship_type||':'||p_source_entity_id::text,0));

  if exists (
    select 1 from public.commercial_relationship_activations
    where organization_id=p_organization_id
      and relationship_type=p_relationship_type
      and source_entity_id=p_source_entity_id
      and target_entity_id=p_target_entity_id
      and status='applied'
  ) then
    select id into activation_id from public.commercial_relationship_activations
    where organization_id=p_organization_id
      and relationship_type=p_relationship_type
      and source_entity_id=p_source_entity_id
      and target_entity_id=p_target_entity_id
      and status='applied';
    return jsonb_build_object('status','already_applied','activation_id',activation_id);
  end if;

  if p_relationship_type='offer_rfq' then
    select conversation_id,rfq_id into source_conversation,existing_target
      from public.offers where organization_id=p_organization_id and id=p_source_entity_id;
    select conversation_id into target_conversation
      from public.rfqs where organization_id=p_organization_id and id=p_target_entity_id;
    if source_conversation is null or source_conversation is distinct from target_conversation then
      return jsonb_build_object('status','blocked','reason','conversation_mismatch');
    end if;
    if existing_target is not null and existing_target<>p_target_entity_id then
      return jsonb_build_object('status','blocked','reason','conflicting_existing_link');
    end if;
    if not private.normalized_line_multiset_matches(p_organization_id,'offer',p_source_entity_id,'rfq',p_target_entity_id) then
      return jsonb_build_object('status','blocked','reason','product_multiset_mismatch');
    end if;
    if (select count(*) from public.rfqs r
        where r.organization_id=p_organization_id and r.conversation_id=source_conversation
          and private.normalized_line_multiset_matches(p_organization_id,'offer',p_source_entity_id,'rfq',r.id))<>1 then
      return jsonb_build_object('status','blocked','reason','candidate_not_unique');
    end if;

    update public.offers set rfq_id=p_target_entity_id
    where organization_id=p_organization_id and id=p_source_entity_id;

    update public.offer_lines ol
    set rfq_line_id=(
      select rl.id from public.rfq_lines rl
      where rl.organization_id=p_organization_id and rl.rfq_id=p_target_entity_id
        and rl.canonical_product_key=ol.canonical_product_key
      limit 1
    )
    where ol.organization_id=p_organization_id and ol.offer_id=p_source_entity_id
      and (select count(*) from public.rfq_lines rl
           where rl.organization_id=p_organization_id and rl.rfq_id=p_target_entity_id
             and rl.canonical_product_key=ol.canonical_product_key)=1;

  elsif p_relationship_type='order_offer' then
    select conversation_id,offer_id into source_conversation,existing_target
      from public.orders where organization_id=p_organization_id and id=p_source_entity_id;
    select conversation_id into target_conversation
      from public.offers where organization_id=p_organization_id and id=p_target_entity_id;
    if source_conversation is null or source_conversation is distinct from target_conversation then
      return jsonb_build_object('status','blocked','reason','conversation_mismatch');
    end if;
    if existing_target is not null and existing_target<>p_target_entity_id then
      return jsonb_build_object('status','blocked','reason','conflicting_existing_link');
    end if;
    if not private.normalized_line_multiset_matches(p_organization_id,'order',p_source_entity_id,'offer',p_target_entity_id) then
      return jsonb_build_object('status','blocked','reason','product_multiset_mismatch');
    end if;
    if (select count(*) from public.offers f
        where f.organization_id=p_organization_id and f.conversation_id=source_conversation
          and private.normalized_line_multiset_matches(p_organization_id,'order',p_source_entity_id,'offer',f.id))<>1 then
      return jsonb_build_object('status','blocked','reason','candidate_not_unique');
    end if;

    update public.orders set offer_id=p_target_entity_id
    where organization_id=p_organization_id and id=p_source_entity_id;

    update public.order_lines ol
    set offer_line_id=(
      select fl.id from public.offer_lines fl
      where fl.organization_id=p_organization_id and fl.offer_id=p_target_entity_id
        and fl.canonical_product_key=ol.canonical_product_key
      limit 1
    )
    where ol.organization_id=p_organization_id and ol.order_id=p_source_entity_id
      and (select count(*) from public.offer_lines fl
           where fl.organization_id=p_organization_id and fl.offer_id=p_target_entity_id
             and fl.canonical_product_key=ol.canonical_product_key)=1;

  else
    select conversation_id,rfq_id into source_conversation,existing_target
      from public.orders where organization_id=p_organization_id and id=p_source_entity_id;
    select conversation_id into target_conversation
      from public.rfqs where organization_id=p_organization_id and id=p_target_entity_id;
    if source_conversation is null or source_conversation is distinct from target_conversation then
      return jsonb_build_object('status','blocked','reason','conversation_mismatch');
    end if;
    if existing_target is not null and existing_target<>p_target_entity_id then
      return jsonb_build_object('status','blocked','reason','conflicting_existing_link');
    end if;
    if not private.normalized_line_multiset_matches(p_organization_id,'order',p_source_entity_id,'rfq',p_target_entity_id) then
      return jsonb_build_object('status','blocked','reason','product_multiset_mismatch');
    end if;
    if (select count(*) from public.rfqs r
        where r.organization_id=p_organization_id and r.conversation_id=source_conversation
          and private.normalized_line_multiset_matches(p_organization_id,'order',p_source_entity_id,'rfq',r.id))<>1 then
      return jsonb_build_object('status','blocked','reason','candidate_not_unique');
    end if;

    update public.orders set rfq_id=p_target_entity_id
    where organization_id=p_organization_id and id=p_source_entity_id;
  end if;

  insert into public.commercial_relationship_activations(
    organization_id,relationship_type,source_entity_id,target_entity_id,
    evidence_type,status,activated_by,metadata
  ) values (
    p_organization_id,p_relationship_type,p_source_entity_id,p_target_entity_id,
    'shared_normalized_conversation_exact_product','applied',actor_id,
    jsonb_build_object('phase','PA2.21','execution_mode','single_explicit')
  )
  returning id into activation_id;

  return jsonb_build_object(
    'status','applied','activation_id',activation_id,
    'relationship_type',p_relationship_type,
    'source_entity_id',p_source_entity_id,
    'target_entity_id',p_target_entity_id,
    'evidence_type','shared_normalized_conversation_exact_product',
    'control_phase','PA2.21','execution_mode','single_explicit'
  );
end;
$$;

revoke all on function private.activate_operational_relationship_impl(uuid,text,uuid,uuid) from public,anon;
grant execute on function private.activate_operational_relationship_impl(uuid,text,uuid,uuid) to authenticated,service_role;

create or replace function public.p1_activate_operational_relationship(
  p_organization_id uuid,
  p_relationship_type text,
  p_source_entity_id uuid,
  p_target_entity_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.activate_operational_relationship_impl(
    p_organization_id,p_relationship_type,p_source_entity_id,p_target_entity_id
  );
$$;

revoke all on function public.p1_activate_operational_relationship(uuid,text,uuid,uuid) from public,anon;
grant execute on function public.p1_activate_operational_relationship(uuid,text,uuid,uuid) to authenticated,service_role;
