create table if not exists public.pilot_human_evidence (
  id bigint generated by default as identity primary key,
  pilot_run_id uuid not null references public.pilot_runs(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  task_type text not null check (task_type in ('search','product_lookup','company_lookup','price_lookup','evidence_check','correction','other')),
  steel_sales_seconds integer not null check (steel_sales_seconds between 1 and 7200),
  previous_method_seconds integer not null check (previous_method_seconds between 1 and 14400),
  comparison text not null check (comparison in ('faster','same','slower')),
  confidence text not null default 'medium' check (confidence in ('low','medium','high')),
  created_at timestamptz not null default now()
);

create index if not exists pilot_human_evidence_run_time_idx
  on public.pilot_human_evidence(pilot_run_id, created_at desc);
create index if not exists pilot_human_evidence_org_time_idx
  on public.pilot_human_evidence(organization_id, created_at desc);

alter table public.pilot_human_evidence enable row level security;
revoke all on table public.pilot_human_evidence from public,anon,authenticated;
grant select,insert,update,delete on table public.pilot_human_evidence to service_role,postgres;
grant usage,select on sequence public.pilot_human_evidence_id_seq to service_role,postgres;

create or replace function private.p1_record_pilot_human_evidence_impl(
  p_organization_id uuid,
  p_task_type text,
  p_steel_sales_seconds integer,
  p_previous_method_seconds integer,
  p_comparison text,
  p_confidence text
)
returns bigint
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_actor uuid := auth.uid();
  v_run_id uuid;
  v_id bigint;
begin
  if v_actor is null then
    raise exception using errcode='28000', message='authentication required';
  end if;
  if p_organization_id is null or not public.is_organization_member(p_organization_id,true) then
    raise exception using errcode='42501', message='active tenant membership required';
  end if;

  select id into v_run_id
  from public.pilot_runs
  where organization_id=p_organization_id and status='active'
  order by started_at desc
  limit 1;

  if v_run_id is null then
    raise exception using errcode='55000', message='active pilot required';
  end if;
  if p_task_type not in ('search','product_lookup','company_lookup','price_lookup','evidence_check','correction','other') then
    raise exception using errcode='22023', message='invalid task type';
  end if;
  if p_comparison not in ('faster','same','slower') then
    raise exception using errcode='22023', message='invalid comparison';
  end if;
  if p_confidence not in ('low','medium','high') then
    raise exception using errcode='22023', message='invalid confidence';
  end if;
  if p_steel_sales_seconds < 1 or p_steel_sales_seconds > 7200
     or p_previous_method_seconds < 1 or p_previous_method_seconds > 14400 then
    raise exception using errcode='22023', message='invalid duration';
  end if;

  insert into public.pilot_human_evidence(
    pilot_run_id,organization_id,actor_user_id,task_type,
    steel_sales_seconds,previous_method_seconds,comparison,confidence
  ) values (
    v_run_id,p_organization_id,v_actor,p_task_type,
    p_steel_sales_seconds,p_previous_method_seconds,p_comparison,p_confidence
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.p1_record_pilot_human_evidence(
  p_organization_id uuid,
  p_task_type text,
  p_steel_sales_seconds integer,
  p_previous_method_seconds integer,
  p_comparison text,
  p_confidence text default 'medium'
)
returns bigint
language sql
security invoker
set search_path to ''
as $$
  select private.p1_record_pilot_human_evidence_impl(
    p_organization_id,p_task_type,p_steel_sales_seconds,p_previous_method_seconds,p_comparison,p_confidence
  );
$$;

create or replace function private.p1_pilot_checkpoint_impl(p_organization_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_actor uuid := auth.uid();
  v_run public.pilot_runs%rowtype;
  v_readiness jsonb;
  v_samples integer;
  v_task_types integer;
  v_faster integer;
  v_same integer;
  v_slower integer;
  v_median_steel numeric;
  v_median_previous numeric;
  v_median_improvement numeric;
begin
  if v_actor is null then
    raise exception using errcode='28000', message='authentication required';
  end if;
  if p_organization_id is null or not public.is_organization_member(p_organization_id,true) then
    raise exception using errcode='42501', message='active tenant membership required';
  end if;

  select * into v_run
  from public.pilot_runs
  where organization_id=p_organization_id and status='active'
  order by started_at desc
  limit 1;

  if v_run.id is null then
    return jsonb_build_object('contract','PA2.37-v1','pilot_active',false,'checkpoint_ready',false);
  end if;

  v_readiness := private.p1_pilot_exit_readiness_impl(p_organization_id,v_run.started_at);

  select
    count(*)::int,
    count(distinct task_type)::int,
    count(*) filter(where comparison='faster')::int,
    count(*) filter(where comparison='same')::int,
    count(*) filter(where comparison='slower')::int,
    percentile_cont(0.5) within group(order by steel_sales_seconds),
    percentile_cont(0.5) within group(order by previous_method_seconds)
  into
    v_samples,v_task_types,v_faster,v_same,v_slower,v_median_steel,v_median_previous
  from public.pilot_human_evidence
  where pilot_run_id=v_run.id;

  if coalesce(v_median_previous,0)>0 then
    v_median_improvement := round((1 - (v_median_steel / v_median_previous)) * 100,1);
  end if;

  return jsonb_build_object(
    'contract','PA2.37-v1',
    'pilot_active',true,
    'pilot_run_id',v_run.id,
    'pilot_started_at',v_run.started_at,
    'quantitative_readiness',v_readiness,
    'human_evidence',jsonb_build_object(
      'sample_count',coalesce(v_samples,0),
      'task_type_count',coalesce(v_task_types,0),
      'faster_count',coalesce(v_faster,0),
      'same_count',coalesce(v_same,0),
      'slower_count',coalesce(v_slower,0),
      'median_steel_sales_seconds',v_median_steel,
      'median_previous_method_seconds',v_median_previous,
      'median_improvement_percent',v_median_improvement,
      'minimum_samples_target',3,
      'minimum_task_types_target',2,
      'evidence_sufficient',coalesce(v_samples,0)>=3 and coalesce(v_task_types,0)>=2
    ),
    'checkpoint_ready',
      coalesce((v_readiness->>'pilot_evidence_ready')::boolean,false)
      and coalesce(v_samples,0)>=3
      and coalesce(v_task_types,0)>=2,
    'interpretation_note',
      'Human time estimates are self-reported evidence and must not be treated as precise causal measurements.'
  );
end;
$$;

create or replace function public.p1_pilot_checkpoint(p_organization_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path to ''
as $$
  select private.p1_pilot_checkpoint_impl(p_organization_id);
$$;

revoke all on function private.p1_record_pilot_human_evidence_impl(uuid,text,integer,integer,text,text) from public,anon;
grant execute on function private.p1_record_pilot_human_evidence_impl(uuid,text,integer,integer,text,text) to authenticated,service_role,postgres;
revoke all on function public.p1_record_pilot_human_evidence(uuid,text,integer,integer,text,text) from public,anon;
grant execute on function public.p1_record_pilot_human_evidence(uuid,text,integer,integer,text,text) to authenticated,service_role,postgres;

revoke all on function private.p1_pilot_checkpoint_impl(uuid) from public,anon;
grant execute on function private.p1_pilot_checkpoint_impl(uuid) to authenticated,service_role,postgres;
revoke all on function public.p1_pilot_checkpoint(uuid) from public,anon;
grant execute on function public.p1_pilot_checkpoint(uuid) to authenticated,service_role,postgres;
