alter table public.buyer_rfq_dispatches drop constraint if exists buyer_rfq_dispatches_status_check;
alter table public.buyer_rfq_dispatches add constraint buyer_rfq_dispatches_status_check check (status in ('queued','sending','sent','delivered','opened','delivery_delayed','responded','declined','bounced','complained','failed','cancelled'));
create table if not exists public.buyer_rfq_quotes(id uuid primary key default gen_random_uuid(),rfq_id uuid not null references public.buyer_rfq_campaigns(id) on delete cascade,supplier_id uuid not null references public.buyer_rfq_suppliers(id) on delete cascade,dispatch_id uuid not null references public.buyer_rfq_dispatches(id) on delete cascade,owner_user_id uuid not null references auth.users(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,revision_no integer not null check(revision_no>=1),status text not null default 'draft' check(status in('draft','submitted','declined','superseded')),currency_code text not null default 'EUR' check(currency_code='EUR'),incoterm text check(incoterm is null or char_length(incoterm)<=32),payment_terms text check(payment_terms is null or char_length(payment_terms)<=240),validity_until date,lead_time_days integer check(lead_time_days is null or lead_time_days between 0 and 3650),delivery_date date,moq_tonnes numeric(18,6) check(moq_tonnes is null or moq_tonnes>=0),notes text check(notes is null or char_length(notes)<=4000),decline_reason text check(decline_reason is null or char_length(decline_reason)<=1000),attachment_bucket text,attachment_path text,attachment_name text,attachment_mime_type text,attachment_size_bytes bigint check(attachment_size_bytes is null or attachment_size_bytes between 1 and 10485760),attachment_upload_count integer not null default 0 check(attachment_upload_count between 0 and 5),submitted_at timestamptz,declined_at timestamptz,superseded_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(dispatch_id,revision_no));
create unique index if not exists buyer_rfq_quotes_current_dispatch_idx on public.buyer_rfq_quotes(dispatch_id) where status in('draft','submitted','declined');
create index if not exists buyer_rfq_quotes_rfq_supplier_idx on public.buyer_rfq_quotes(rfq_id,supplier_id,revision_no desc);
create index if not exists buyer_rfq_quotes_owner_created_idx on public.buyer_rfq_quotes(owner_user_id,created_at desc);
create table if not exists public.buyer_rfq_quote_lines(id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.buyer_rfq_quotes(id) on delete cascade,rfq_line_id uuid not null references public.buyer_distinta_lines(id) on delete restrict,line_position integer not null,response_status text not null default 'quoted' check(response_status in('quoted','not_available')),price_basis text check(price_basis is null or price_basis in('eur_t','eur_m')),unit_price numeric(18,6) check(unit_price is null or unit_price>0),normalized_eur_t numeric(18,6) check(normalized_eur_t is null or normalized_eur_t>0),normalized_eur_m numeric(18,6) check(normalized_eur_m is null or normalized_eur_m>0),offered_quantity numeric(18,6) check(offered_quantity is null or offered_quantity>0),offered_quantity_mode text check(offered_quantity_mode is null or offered_quantity_mode in('meters','tonnes','bars')),moq_tonnes numeric(18,6) check(moq_tonnes is null or moq_tonnes>=0),lead_time_days integer check(lead_time_days is null or lead_time_days between 0 and 3650),delivery_date date,notes text check(notes is null or char_length(notes)<=2000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(quote_id,rfq_line_id),unique(quote_id,line_position));
create index if not exists buyer_rfq_quote_lines_quote_idx on public.buyer_rfq_quote_lines(quote_id,line_position);
alter table public.buyer_rfq_quotes enable row level security;
alter table public.buyer_rfq_quote_lines enable row level security;
revoke all on public.buyer_rfq_quotes from anon,authenticated;
revoke all on public.buyer_rfq_quote_lines from anon,authenticated;
grant select on public.buyer_rfq_quotes to authenticated;
grant select on public.buyer_rfq_quote_lines to authenticated;
create policy buyer_rfq_quotes_owner_select on public.buyer_rfq_quotes for select to authenticated using(owner_user_id=(select auth.uid()));
create policy buyer_rfq_quote_lines_owner_select on public.buyer_rfq_quote_lines for select to authenticated using(exists(select 1 from public.buyer_rfq_quotes q where q.id=buyer_rfq_quote_lines.quote_id and q.owner_user_id=(select auth.uid())));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('rfq-supplier-offers','rfq-supplier-offers',false,10485760,array['application/pdf','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']::text[]) on conflict(id) do update set public=false,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists rfqh4_buyer_offer_attachment_select on storage.objects;
create policy rfqh4_buyer_offer_attachment_select on storage.objects for select to authenticated using(bucket_id='rfq-supplier-offers' and exists(select 1 from public.buyer_rfq_quotes q where q.owner_user_id=(select auth.uid()) and q.id::text=(storage.foldername(name))[1]));
create or replace function rfqh_secure.rfqh4_get_portal_impl(p_token_hash text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_base jsonb; v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_quote public.buyer_rfq_quotes%rowtype; v_lines jsonb; v_quote_lines jsonb:='[]'::jsonb;
begin
 v_base:=rfqh_secure.rfqh3_open_invite_impl(p_token_hash); if coalesce((v_base->>'valid')::boolean,false)=false then return v_base; end if;
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained') limit 1; if not found then return jsonb_build_object('valid',false); end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id order by q.revision_no desc limit 1;
 select coalesce(jsonb_agg(jsonb_build_object('line_id',l.id,'position',l.line_position,'description',l.description,'standard',l.standard_code,'grade',l.grade_code,'finish',l.finish_code,'quantity_mode',l.quantity_mode,'quantity',l.quantity,'bar_length_m',l.bar_length_m,'weight_kg_m',l.weight_kg_m,'line_meters',l.line_meters,'line_tonnes',l.line_tonnes,'note',l.note) order by l.line_position),'[]'::jsonb) into v_lines from public.buyer_distinta_lines l where l.distinta_id=v_rfq.source_distinta_id;
 if v_quote.id is not null then select coalesce(jsonb_agg(jsonb_build_object('line_id',ql.rfq_line_id,'position',ql.line_position,'response_status',ql.response_status,'price_basis',ql.price_basis,'unit_price',ql.unit_price,'normalized_eur_t',ql.normalized_eur_t,'normalized_eur_m',ql.normalized_eur_m,'offered_quantity',ql.offered_quantity,'offered_quantity_mode',ql.offered_quantity_mode,'moq_tonnes',ql.moq_tonnes,'lead_time_days',ql.lead_time_days,'delivery_date',ql.delivery_date,'notes',ql.notes) order by ql.line_position),'[]'::jsonb) into v_quote_lines from public.buyer_rfq_quote_lines ql where ql.quote_id=v_quote.id; end if;
 return v_base||jsonb_build_object('lines',v_lines,'can_respond',(v_rfq.status in('launched','collecting') and(v_rfq.due_at is null or v_rfq.due_at>now()) and v_dispatch.status not in('declined','cancelled','failed','bounced','complained')),'quote',case when v_quote.id is null then null else jsonb_build_object('id',v_quote.id,'revision_no',v_quote.revision_no,'status',v_quote.status,'currency_code',v_quote.currency_code,'incoterm',v_quote.incoterm,'payment_terms',v_quote.payment_terms,'validity_until',v_quote.validity_until,'lead_time_days',v_quote.lead_time_days,'delivery_date',v_quote.delivery_date,'moq_tonnes',v_quote.moq_tonnes,'notes',v_quote.notes,'decline_reason',v_quote.decline_reason,'attachment_name',v_quote.attachment_name,'attachment_mime_type',v_quote.attachment_mime_type,'attachment_size_bytes',v_quote.attachment_size_bytes,'submitted_at',v_quote.submitted_at,'declined_at',v_quote.declined_at,'lines',v_quote_lines) end);
end$$;
revoke all on function rfqh_secure.rfqh4_get_portal_impl(text) from public; grant execute on function rfqh_secure.rfqh4_get_portal_impl(text) to anon,authenticated;
create or replace function public.rfqh4_get_portal(p_token_hash text) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_get_portal_impl(p_token_hash)$$;
revoke all on function public.rfqh4_get_portal(text) from public,anon,authenticated; grant execute on function public.rfqh4_get_portal(text) to anon,authenticated;
create or replace function rfqh_secure.rfqh4_save_quote_impl(p_token_hash text,p_header jsonb,p_lines jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_quote public.buyer_rfq_quotes%rowtype; v_row jsonb; v_source public.buyer_distinta_lines%rowtype; v_line_id uuid; v_status text; v_basis text; v_unit numeric; v_norm_t numeric; v_norm_m numeric;
begin
 if jsonb_typeof(coalesce(p_header,'{}'::jsonb))<>'object' then raise exception 'Quote header must be an object'; end if; if jsonb_typeof(coalesce(p_lines,'[]'::jsonb))<>'array' then raise exception 'Quote lines must be an array'; end if; if jsonb_array_length(coalesce(p_lines,'[]'::jsonb))>500 then raise exception 'Too many quote lines'; end if;
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained','declined') for update; if not found then raise exception 'RFQ invite is not available' using errcode='42501'; end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id for update; if v_rfq.status not in('launched','collecting') then raise exception 'RFQ is not open for responses'; end if; if v_rfq.due_at is not null and v_rfq.due_at<=now() then raise exception 'RFQ deadline has passed'; end if;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status in('draft','submitted','declined') order by q.revision_no desc limit 1 for update; if v_quote.status='submitted' then raise exception 'Start a revision before editing a submitted quote'; end if; if v_quote.status='declined' then raise exception 'Declined RFQ cannot be edited'; end if;
 if v_quote.id is null then insert into public.buyer_rfq_quotes(rfq_id,supplier_id,dispatch_id,owner_user_id,organization_id,revision_no,status) values(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.id,v_dispatch.owner_user_id,v_dispatch.organization_id,1,'draft') returning * into v_quote; perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_draft_created',jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no),null); end if;
 update public.buyer_rfq_quotes set incoterm=nullif(left(btrim(coalesce(p_header->>'incoterm','')),32),''),payment_terms=nullif(left(btrim(coalesce(p_header->>'payment_terms','')),240),''),validity_until=nullif(p_header->>'validity_until','')::date,lead_time_days=nullif(p_header->>'lead_time_days','')::integer,delivery_date=nullif(p_header->>'delivery_date','')::date,moq_tonnes=nullif(p_header->>'moq_tonnes','')::numeric,notes=nullif(left(btrim(coalesce(p_header->>'notes','')),4000),''),updated_at=now() where id=v_quote.id returning * into v_quote;
 if v_quote.validity_until is not null and v_quote.validity_until<current_date then raise exception 'Quote validity date cannot be in the past'; end if; if v_quote.delivery_date is not null and v_quote.delivery_date<current_date then raise exception 'Delivery date cannot be in the past'; end if;
 if(select count(*) from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)))<>(select count(distinct value->>'line_id') from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb))) then raise exception 'Duplicate quote line'; end if;
 delete from public.buyer_rfq_quote_lines where quote_id=v_quote.id;
 for v_row in select value from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) loop
   v_line_id:=nullif(v_row->>'line_id','')::uuid; if v_line_id is null then raise exception 'Quote line ID is required'; end if;
   select * into v_source from public.buyer_distinta_lines l where l.id=v_line_id and l.distinta_id=v_rfq.source_distinta_id; if not found then raise exception 'Quote line does not belong to this RFQ'; end if;
   v_status:=coalesce(nullif(v_row->>'response_status',''),'quoted'); if v_status not in('quoted','not_available') then raise exception 'Invalid quote line response status'; end if;
   v_basis:=nullif(v_row->>'price_basis',''); if v_basis is not null and v_basis not in('eur_t','eur_m') then raise exception 'Invalid price basis'; end if;
   v_unit:=nullif(v_row->>'unit_price','')::numeric; if v_unit is not null and v_unit<=0 then raise exception 'Unit price must be positive'; end if;
   v_norm_t:=null; v_norm_m:=null; if v_status='quoted' and v_unit is not null and v_basis is not null then if v_basis='eur_t' then v_norm_t:=v_unit; v_norm_m:=v_unit*v_source.weight_kg_m/1000; else if v_source.weight_kg_m<=0 then raise exception 'Line weight must be positive'; end if; v_norm_m:=v_unit; v_norm_t:=v_unit*1000/v_source.weight_kg_m; end if; end if;
   insert into public.buyer_rfq_quote_lines(quote_id,rfq_line_id,line_position,response_status,price_basis,unit_price,normalized_eur_t,normalized_eur_m,offered_quantity,offered_quantity_mode,moq_tonnes,lead_time_days,delivery_date,notes) values(v_quote.id,v_source.id,v_source.line_position,v_status,case when v_status='quoted' then v_basis end,case when v_status='quoted' then v_unit end,case when v_status='quoted' then v_norm_t end,case when v_status='quoted' then v_norm_m end,nullif(v_row->>'offered_quantity','')::numeric,nullif(v_row->>'offered_quantity_mode',''),nullif(v_row->>'moq_tonnes','')::numeric,nullif(v_row->>'lead_time_days','')::integer,nullif(v_row->>'delivery_date','')::date,nullif(left(btrim(coalesce(v_row->>'notes','')),2000),''));
 end loop;
 perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_draft_saved',jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'line_count',jsonb_array_length(coalesce(p_lines,'[]'::jsonb))),null);
 return jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'status','draft');
end$$;
revoke all on function rfqh_secure.rfqh4_save_quote_impl(text,jsonb,jsonb) from public; grant execute on function rfqh_secure.rfqh4_save_quote_impl(text,jsonb,jsonb) to anon,authenticated;
create or replace function public.rfqh4_save_quote(p_token_hash text,p_header jsonb default '{}'::jsonb,p_lines jsonb default '[]'::jsonb) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_save_quote_impl(p_token_hash,p_header,p_lines)$$;
revoke all on function public.rfqh4_save_quote(text,jsonb,jsonb) from public,anon,authenticated; grant execute on function public.rfqh4_save_quote(text,jsonb,jsonb) to anon,authenticated;
create or replace function rfqh_secure.rfqh4_submit_quote_impl(p_token_hash text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_quote public.buyer_rfq_quotes%rowtype; v_source_count int; v_quote_count int; v_quoted_count int; v_unavailable_count int;
begin
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained','declined') for update; if not found then raise exception 'RFQ invite is not available' using errcode='42501'; end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id for update; if v_rfq.status not in('launched','collecting') then raise exception 'RFQ is not open for responses'; end if; if v_rfq.due_at is not null and v_rfq.due_at<=now() then raise exception 'RFQ deadline has passed'; end if;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status='draft' order by q.revision_no desc limit 1 for update; if not found then raise exception 'Save a draft before submitting'; end if;
 select count(*)::int into v_source_count from public.buyer_distinta_lines l where l.distinta_id=v_rfq.source_distinta_id;
 select count(*)::int,count(*) filter(where response_status='quoted')::int,count(*) filter(where response_status='not_available')::int into v_quote_count,v_quoted_count,v_unavailable_count from public.buyer_rfq_quote_lines ql where ql.quote_id=v_quote.id;
 if v_quote_count<>v_source_count then raise exception 'Every RFQ line requires a response'; end if; if v_quoted_count<1 then raise exception 'Quote at least one RFQ line or decline the RFQ'; end if;
 if exists(select 1 from public.buyer_rfq_quote_lines ql where ql.quote_id=v_quote.id and ql.response_status='quoted' and(ql.price_basis is null or ql.unit_price is null or ql.normalized_eur_t is null or ql.normalized_eur_m is null)) then raise exception 'Every quoted line requires a valid price'; end if;
 update public.buyer_rfq_quotes set status='submitted',submitted_at=now(),updated_at=now() where id=v_quote.id;
 update public.buyer_rfq_suppliers set status='responded',responded_at=coalesce(responded_at,now()),updated_at=now() where id=v_dispatch.supplier_id;
 update public.buyer_rfq_dispatches set status='responded',updated_at=now() where id=v_dispatch.id;
 update public.buyer_rfq_campaigns set status='collecting',updated_at=now() where id=v_dispatch.rfq_id and status in('launched','collecting');
 perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_submitted',jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'quoted_lines',v_quoted_count,'unavailable_lines',v_unavailable_count),null);
 return jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'status','submitted');
end$$;
revoke all on function rfqh_secure.rfqh4_submit_quote_impl(text) from public; grant execute on function rfqh_secure.rfqh4_submit_quote_impl(text) to anon,authenticated;
create or replace function public.rfqh4_submit_quote(p_token_hash text) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_submit_quote_impl(p_token_hash)$$;
revoke all on function public.rfqh4_submit_quote(text) from public,anon,authenticated; grant execute on function public.rfqh4_submit_quote(text) to anon,authenticated;
create or replace function rfqh_secure.rfqh4_decline_impl(p_token_hash text,p_reason text default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_quote public.buyer_rfq_quotes%rowtype; v_revision int;
begin
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained') for update; if not found then raise exception 'RFQ invite is not available' using errcode='42501'; end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id for update; if v_rfq.status not in('launched','collecting') then raise exception 'RFQ is not open for responses'; end if; if v_rfq.due_at is not null and v_rfq.due_at<=now() then raise exception 'RFQ deadline has passed'; end if;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status in('draft','submitted','declined') order by q.revision_no desc limit 1 for update;
 if v_quote.status='submitted' then raise exception 'Submitted quote cannot be declined; start a revision instead'; end if; if v_quote.status='declined' then return jsonb_build_object('quote_id',v_quote.id,'status','declined'); end if;
 if v_quote.id is null then select coalesce(max(q.revision_no),0)+1 into v_revision from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id; insert into public.buyer_rfq_quotes(rfq_id,supplier_id,dispatch_id,owner_user_id,organization_id,revision_no,status,decline_reason,declined_at) values(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.id,v_dispatch.owner_user_id,v_dispatch.organization_id,v_revision,'declined',nullif(left(btrim(coalesce(p_reason,'')),1000),''),now()) returning * into v_quote; else update public.buyer_rfq_quotes set status='declined',decline_reason=nullif(left(btrim(coalesce(p_reason,'')),1000),''),declined_at=now(),updated_at=now() where id=v_quote.id returning * into v_quote; end if;
 update public.buyer_rfq_suppliers set status='declined',declined_at=coalesce(declined_at,now()),updated_at=now() where id=v_dispatch.supplier_id; update public.buyer_rfq_dispatches set status='declined',updated_at=now() where id=v_dispatch.id;
 perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_declined',jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'reason',v_quote.decline_reason),null);
 return jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'status','declined');
end$$;
revoke all on function rfqh_secure.rfqh4_decline_impl(text,text) from public; grant execute on function rfqh_secure.rfqh4_decline_impl(text,text) to anon,authenticated;
create or replace function public.rfqh4_decline(p_token_hash text,p_reason text default null) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_decline_impl(p_token_hash,p_reason)$$;
revoke all on function public.rfqh4_decline(text,text) from public,anon,authenticated; grant execute on function public.rfqh4_decline(text,text) to anon,authenticated;
create or replace function rfqh_secure.rfqh4_start_revision_impl(p_token_hash text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_current public.buyer_rfq_quotes%rowtype; v_new public.buyer_rfq_quotes%rowtype;
begin
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status='responded' for update; if not found then raise exception 'Submitted RFQ response not found' using errcode='42501'; end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id for update; if v_rfq.status not in('launched','collecting') then raise exception 'RFQ is not open for revisions'; end if; if v_rfq.due_at is not null and v_rfq.due_at<=now() then raise exception 'RFQ deadline has passed'; end if;
 select * into v_current from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status='submitted' order by q.revision_no desc limit 1 for update; if not found then raise exception 'Submitted quote not found'; end if;
 update public.buyer_rfq_quotes set status='superseded',superseded_at=now(),updated_at=now() where id=v_current.id;
 insert into public.buyer_rfq_quotes(rfq_id,supplier_id,dispatch_id,owner_user_id,organization_id,revision_no,status,currency_code,incoterm,payment_terms,validity_until,lead_time_days,delivery_date,moq_tonnes,notes) values(v_current.rfq_id,v_current.supplier_id,v_current.dispatch_id,v_current.owner_user_id,v_current.organization_id,v_current.revision_no+1,'draft',v_current.currency_code,v_current.incoterm,v_current.payment_terms,v_current.validity_until,v_current.lead_time_days,v_current.delivery_date,v_current.moq_tonnes,v_current.notes) returning * into v_new;
 insert into public.buyer_rfq_quote_lines(quote_id,rfq_line_id,line_position,response_status,price_basis,unit_price,normalized_eur_t,normalized_eur_m,offered_quantity,offered_quantity_mode,moq_tonnes,lead_time_days,delivery_date,notes) select v_new.id,rfq_line_id,line_position,response_status,price_basis,unit_price,normalized_eur_t,normalized_eur_m,offered_quantity,offered_quantity_mode,moq_tonnes,lead_time_days,delivery_date,notes from public.buyer_rfq_quote_lines where quote_id=v_current.id;
 perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_revision_started',jsonb_build_object('previous_quote_id',v_current.id,'quote_id',v_new.id,'revision_no',v_new.revision_no),null);
 return jsonb_build_object('quote_id',v_new.id,'revision_no',v_new.revision_no,'status','draft');
end$$;
revoke all on function rfqh_secure.rfqh4_start_revision_impl(text) from public; grant execute on function rfqh_secure.rfqh4_start_revision_impl(text) to anon,authenticated;
create or replace function public.rfqh4_start_revision(p_token_hash text) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_start_revision_impl(p_token_hash)$$;
revoke all on function public.rfqh4_start_revision(text) from public,anon,authenticated; grant execute on function public.rfqh4_start_revision(text) to anon,authenticated;
create or replace function rfqh_secure.rfqh4_prepare_attachment_impl(p_token_hash text,p_file_name text,p_mime_type text,p_size_bytes bigint) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_rfq public.buyer_rfq_campaigns%rowtype; v_quote public.buyer_rfq_quotes%rowtype; v_revision int;
begin
 if p_size_bytes is null or p_size_bytes<1 or p_size_bytes>10485760 then raise exception 'Attachment must be between 1 byte and 10 MB'; end if; if p_mime_type not in('application/pdf','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') then raise exception 'Unsupported attachment type'; end if;
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained','declined') for update; if not found then raise exception 'RFQ invite is not available' using errcode='42501'; end if;
 select * into v_rfq from public.buyer_rfq_campaigns r where r.id=v_dispatch.rfq_id for update; if v_rfq.status not in('launched','collecting') then raise exception 'RFQ is not open for attachments'; end if; if v_rfq.due_at is not null and v_rfq.due_at<=now() then raise exception 'RFQ deadline has passed'; end if;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status='draft' order by q.revision_no desc limit 1 for update;
 if not found then if exists(select 1 from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status='submitted') then raise exception 'Start a revision before replacing a submitted attachment'; end if; select coalesce(max(q.revision_no),0)+1 into v_revision from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id; insert into public.buyer_rfq_quotes(rfq_id,supplier_id,dispatch_id,owner_user_id,organization_id,revision_no,status) values(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.id,v_dispatch.owner_user_id,v_dispatch.organization_id,v_revision,'draft') returning * into v_quote; end if;
 if v_quote.attachment_upload_count>=5 then raise exception 'Attachment upload limit reached'; end if; return jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'old_attachment_path',v_quote.attachment_path,'file_name',left(btrim(coalesce(p_file_name,'offer')),180));
end$$;
revoke all on function rfqh_secure.rfqh4_prepare_attachment_impl(text,text,text,bigint) from public,anon,authenticated; grant usage on schema rfqh_secure to service_role; grant execute on function rfqh_secure.rfqh4_prepare_attachment_impl(text,text,text,bigint) to service_role;
create or replace function public.rfqh4_prepare_attachment(p_token_hash text,p_file_name text,p_mime_type text,p_size_bytes bigint) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_prepare_attachment_impl(p_token_hash,p_file_name,p_mime_type,p_size_bytes)$$;
revoke all on function public.rfqh4_prepare_attachment(text,text,text,bigint) from public,anon,authenticated; grant execute on function public.rfqh4_prepare_attachment(text,text,text,bigint) to service_role;
create or replace function rfqh_secure.rfqh4_record_attachment_impl(p_token_hash text,p_storage_path text,p_file_name text,p_mime_type text,p_size_bytes bigint) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_dispatch public.buyer_rfq_dispatches%rowtype; v_quote public.buyer_rfq_quotes%rowtype;
begin
 select * into v_dispatch from public.buyer_rfq_dispatches d where d.token_hash=p_token_hash and d.status not in('cancelled','failed','bounced','complained','declined') limit 1; if not found then raise exception 'RFQ invite is not available' using errcode='42501'; end if;
 select * into v_quote from public.buyer_rfq_quotes q where q.dispatch_id=v_dispatch.id and q.status='draft' order by q.revision_no desc limit 1 for update; if not found then raise exception 'Draft quote not found'; end if;
 if p_storage_path not like(v_quote.id::text||'/v'||v_quote.revision_no::text||'/%') then raise exception 'Invalid attachment path'; end if; if p_size_bytes is null or p_size_bytes<1 or p_size_bytes>10485760 then raise exception 'Invalid attachment size'; end if; if p_mime_type not in('application/pdf','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') then raise exception 'Unsupported attachment type'; end if; if v_quote.attachment_upload_count>=5 then raise exception 'Attachment upload limit reached'; end if;
 update public.buyer_rfq_quotes set attachment_bucket='rfq-supplier-offers',attachment_path=p_storage_path,attachment_name=left(btrim(coalesce(p_file_name,'offer')),180),attachment_mime_type=p_mime_type,attachment_size_bytes=p_size_bytes,attachment_upload_count=attachment_upload_count+1,updated_at=now() where id=v_quote.id returning * into v_quote;
 perform private.rfqh3_log_event(v_dispatch.rfq_id,v_dispatch.supplier_id,v_dispatch.owner_user_id,v_dispatch.organization_id,'quote_attachment_uploaded',jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'file_name',v_quote.attachment_name,'size_bytes',p_size_bytes),null);
 return jsonb_build_object('quote_id',v_quote.id,'revision_no',v_quote.revision_no,'attachment_name',v_quote.attachment_name);
end$$;
revoke all on function rfqh_secure.rfqh4_record_attachment_impl(text,text,text,text,bigint) from public,anon,authenticated; grant execute on function rfqh_secure.rfqh4_record_attachment_impl(text,text,text,text,bigint) to service_role;
create or replace function public.rfqh4_record_attachment(p_token_hash text,p_storage_path text,p_file_name text,p_mime_type text,p_size_bytes bigint) returns jsonb language sql security invoker set search_path='' as $$select rfqh_secure.rfqh4_record_attachment_impl(p_token_hash,p_storage_path,p_file_name,p_mime_type,p_size_bytes)$$;
revoke all on function public.rfqh4_record_attachment(text,text,text,text,bigint) from public,anon,authenticated; grant execute on function public.rfqh4_record_attachment(text,text,text,text,bigint) to service_role;
notify pgrst,'reload schema';
