-- PA2.23 — Structured Conversation / Message Coverage Expansion.
-- Deterministic normalization of one commercial thread into one Conversation.
-- Message synthesis is explicitly forbidden because the legacy source only exposes aggregate email_count.

create unique index if not exists conversations_org_external_thread_uidx
on public.conversations(organization_id,external_thread_id)
where external_thread_id is not null;

create table if not exists public.commercial_conversation_expansions (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  commercial_thread_id uuid not null,
  source_conversation_id uuid not null,
  conversation_id uuid not null,
  status text not null check (status in ('applied')),
  expanded_by uuid not null references auth.users(id) on delete restrict,
  expanded_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (organization_id,commercial_thread_id),
  unique (organization_id,conversation_id),
  foreign key (commercial_thread_id)
    references public.commercial_threads(id),
  foreign key (conversation_id)
    references public.conversations(id)
);

alter table public.commercial_conversation_expansions enable row level security;

drop policy if exists "members can read commercial conversation expansions"
on public.commercial_conversation_expansions;
create policy "members can read commercial conversation expansions"
on public.commercial_conversation_expansions
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_conversation_expansions from public,anon;
grant select on table public.commercial_conversation_expansions to authenticated,service_role;
grant usage,select on sequence public.commercial_conversation_expansions_id_seq to service_role;

create or replace function public.p1_structured_conversation_coverage_readiness(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with threads as (
      select
        t.id commercial_thread_id,
        t.owner_id,
        t.source_conversation_id,
        t.subject,
        t.started_at,
        t.last_activity_at,
        t.email_count,
        c.id existing_conversation_id,
        case
          when c.id is not null then 'already_normalized'
          when t.owner_id is null then 'blocked'
          when t.source_conversation_id is null then 'blocked'
          else 'ready'
        end readiness_status,
        array_remove(array[
          case when t.owner_id is null then 'missing_owner' end,
          case when t.source_conversation_id is null then 'missing_source_conversation_id' end
        ]::text[],null) reasons
      from public.commercial_threads t
      left join public.conversations c
        on c.organization_id=t.organization_id
       and c.external_thread_id=t.source_conversation_id::text
      where t.organization_id=p_organization_id
    )
    select jsonb_build_object(
      'summary',jsonb_build_object(
        'commercial_threads',(select count(*) from threads),
        'conversation_ready',(select count(*) from threads where readiness_status='ready'),
        'conversation_already_normalized',(select count(*) from threads where readiness_status='already_normalized'),
        'conversation_blocked',(select count(*) from threads where readiness_status='blocked'),
        'message_ready',0,
        'message_identity_unavailable',(select count(*) from threads),
        'source_email_count',coalesce((select sum(email_count) from threads),0)
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'commercial_thread_id',commercial_thread_id,
          'source_conversation_id',source_conversation_id,
          'subject',subject,
          'started_at',started_at,
          'last_activity_at',last_activity_at,
          'email_count',email_count,
          'readiness_status',readiness_status,
          'reasons',to_jsonb(reasons)
        ) order by last_activity_at desc nulls last,commercial_thread_id)
        from (
          select *
          from threads
          where readiness_status='ready'
          limit greatest(1,least(coalesce(p_limit,100),500))
        ) q
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'conversation_identity','commercial_threads.source_conversation_id -> conversations.external_thread_id',
        'conversation_subject_copy',true,
        'conversation_timestamps_copy',true,
        'company_inference',false,
        'message_synthesis',false,
        'message_reason','no structured per-message identity in legacy source',
        'bulk_auto_expansion',false
      )
    )
  );
end;
$$;

revoke all on function public.p1_structured_conversation_coverage_readiness(uuid,integer)
from public,anon;
grant execute on function public.p1_structured_conversation_coverage_readiness(uuid,integer)
to authenticated,service_role;

create or replace function private.expand_structured_conversation_impl(
  p_organization_id uuid,
  p_commercial_thread_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  source_thread public.commercial_threads%rowtype;
  existing_conversation_id uuid;
  new_conversation_id uuid := gen_random_uuid();
  expansion_id bigint;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'conversation-expansion:'||p_organization_id::text||':'||p_commercial_thread_id::text,0));

  select * into source_thread
  from public.commercial_threads
  where organization_id=p_organization_id
    and id=p_commercial_thread_id;

  if not found then
    raise exception 'Commercial thread not found in organization';
  end if;

  if source_thread.owner_id is null then
    return jsonb_build_object('status','blocked','reason','missing_owner');
  end if;

  if source_thread.source_conversation_id is null then
    return jsonb_build_object('status','blocked','reason','missing_source_conversation_id');
  end if;

  select id into existing_conversation_id
  from public.conversations
  where organization_id=p_organization_id
    and external_thread_id=source_thread.source_conversation_id::text
  limit 1;

  if existing_conversation_id is not null then
    return jsonb_build_object(
      'status','already_normalized',
      'commercial_thread_id',p_commercial_thread_id,
      'conversation_id',existing_conversation_id,
      'source_conversation_id',source_thread.source_conversation_id
    );
  end if;

  insert into public.conversations(
    id,owner_id,company_id,subject,external_thread_id,status,
    started_at,last_activity_at,organization_id
  ) values (
    new_conversation_id,
    source_thread.owner_id,
    null,
    source_thread.subject,
    source_thread.source_conversation_id::text,
    'open',
    source_thread.started_at,
    source_thread.last_activity_at,
    p_organization_id
  );

  insert into public.commercial_conversation_expansions(
    organization_id,commercial_thread_id,source_conversation_id,
    conversation_id,status,expanded_by,metadata
  ) values (
    p_organization_id,
    p_commercial_thread_id,
    source_thread.source_conversation_id,
    new_conversation_id,
    'applied',
    actor_id,
    jsonb_build_object(
      'phase','PA2.23',
      'identity_method','exact_source_conversation_id',
      'company_inference',false,
      'message_synthesis',false,
      'execution_mode','single_thread_explicit'
    )
  )
  returning id into expansion_id;

  return jsonb_build_object(
    'status','expanded',
    'expansion_id',expansion_id,
    'commercial_thread_id',p_commercial_thread_id,
    'conversation_id',new_conversation_id,
    'source_conversation_id',source_thread.source_conversation_id,
    'control_phase','PA2.23',
    'execution_mode','single_thread_explicit'
  );
end;
$$;

revoke all on function private.expand_structured_conversation_impl(uuid,uuid)
from public,anon;
grant execute on function private.expand_structured_conversation_impl(uuid,uuid)
to authenticated,service_role;

create or replace function public.p1_expand_structured_conversation(
  p_organization_id uuid,
  p_commercial_thread_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.expand_structured_conversation_impl(
    p_organization_id,p_commercial_thread_id
  );
$$;

revoke all on function public.p1_expand_structured_conversation(uuid,uuid)
from public,anon;
grant execute on function public.p1_expand_structured_conversation(uuid,uuid)
to authenticated,service_role;
