-- PA2.26 — Offer Evidence Remediation Readiness.
-- Classifies blocked Offer evidence without relaxing PA2.17 / PA2.25.
-- No observation values are corrected here. Source-email reparse remains a future explicit action.

create table if not exists public.commercial_offer_remediation_queue (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  thread_id uuid not null references public.commercial_threads(id) on delete restrict,
  category text not null check (category in (
    'direction_conflict',
    'mixed_complete_unique_incomplete',
    'product_identity_gap',
    'source_reparse_required'
  )),
  recommended_action text not null check (recommended_action in (
    'manual_direction_review',
    'manual_scope_review',
    'product_identity_review',
    'source_email_reparse'
  )),
  status text not null default 'pending' check (status in ('pending','resolved','dismissed')),
  evidence_snapshot jsonb not null default '{}'::jsonb,
  enrolled_by uuid not null references auth.users(id) on delete restrict,
  enrolled_at timestamptz not null default now(),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolution_notes text,
  unique (organization_id,thread_id)
);

alter table public.commercial_offer_remediation_queue enable row level security;

drop policy if exists "members can read commercial offer remediation queue"
on public.commercial_offer_remediation_queue;
create policy "members can read commercial offer remediation queue"
on public.commercial_offer_remediation_queue
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_offer_remediation_queue from public,anon;
grant select on table public.commercial_offer_remediation_queue to authenticated,service_role;
grant usage,select on sequence public.commercial_offer_remediation_queue_id_seq to service_role;

create or replace function public.p1_offer_evidence_remediation_readiness(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with offered as (
      select
        o.*,
        coalesce((
          coalesce(o.confidence,0)>=0.90
          and o.direction='outbound'
          and o.canonical_product_id is not null
          and o.canonical_product_key is not null
          and o.quantity is not null
          and o.quantity_unit is not null
          and o.price_value is not null
          and o.price_unit is not null
          and o.currency is not null
          and nullif(btrim(coalesce(o.source_text,'')),'') is not null
          and not exists (
            select 1
            from public.commercial_review_queue q
            where q.organization_id=o.organization_id
              and q.observation_id=o.id
              and q.status='pending'
          )
        ),false) complete_line,
        (
          coalesce(o.source_text,'') ~* '(€|eur|euro)'
          or coalesce(o.source_clause,'') ~* '(€|eur|euro)'
        ) explicit_currency_marker,
        (
          coalesce(o.source_text,'') ~* '(\bton\.?\b|\btons?\b|\bbarre?\b|\bverghe?\b|\bpacch[io]\b|\bmt\.?\b|\bmetri\b)'
          or coalesce(o.source_clause,'') ~* '(\bton\.?\b|\btons?\b|\bbarre?\b|\bverghe?\b|\bpacch[io]\b|\bmt\.?\b|\bmetri\b)'
        ) explicit_quantity_marker
      from public.commercial_observations o
      where o.organization_id=p_organization_id
        and o.item_role='offered'
    ),
    thread_stats as (
      select
        o.thread_id,
        count(*)::int observation_count,
        count(*) filter(where o.complete_line)::int complete_count,
        count(*) filter(where not o.complete_line)::int incomplete_count,
        count(*) filter(where o.direction is distinct from 'outbound')::int direction_issue_count,
        count(*) filter(where coalesce(o.confidence,0)<0.90)::int low_confidence_count,
        count(*) filter(where o.canonical_product_id is null or o.canonical_product_key is null)::int product_identity_gap_count,
        count(*) filter(where o.quantity is null or o.quantity_unit is null)::int quantity_gap_count,
        count(*) filter(where o.price_value is null or o.price_unit is null)::int price_gap_count,
        count(*) filter(where o.currency is null)::int currency_gap_count,
        count(*) filter(
          where (o.price_value is null or o.price_unit is null or o.currency is null)
            and o.explicit_currency_marker
        )::int explicit_price_currency_marker_gap_count,
        count(*) filter(
          where (o.quantity is null or o.quantity_unit is null)
            and o.explicit_quantity_marker
        )::int explicit_quantity_marker_gap_count,
        count(*) filter(
          where exists (
            select 1 from public.commercial_review_queue q
            where q.organization_id=o.organization_id
              and q.observation_id=o.id
              and q.status='pending'
          )
        )::int pending_review_count,
        count(*) filter(
          where exists (
            select 1 from public.current_commercial_entity_promotions p
            where p.organization_id=o.organization_id
              and p.observation_id=o.id
              and p.entity_type='offer_line'
              and p.status='applied'
          )
        )::int promoted_count,
        min(o.source_filename) source_filename
      from offered o
      group by o.thread_id
    ),
    classified as (
      select
        s.*,
        t.subject,
        t.source_conversation_id,
        c.id conversation_id,
        q.id queue_id,
        q.status queue_status,
        case
          when s.direction_issue_count>0
            then 'direction_conflict'
          when s.complete_count>0 and s.complete_count<s.observation_count
            then 'mixed_complete_unique_incomplete'
          when s.product_identity_gap_count>0
            then 'product_identity_gap'
          when s.price_gap_count>0 or s.currency_gap_count>0 or s.quantity_gap_count>0
            then 'source_reparse_required'
          else null
        end category,
        case
          when s.direction_issue_count>0
            then 'manual_direction_review'
          when s.complete_count>0 and s.complete_count<s.observation_count
            then 'manual_scope_review'
          when s.product_identity_gap_count>0
            then 'product_identity_review'
          when s.price_gap_count>0 or s.currency_gap_count>0 or s.quantity_gap_count>0
            then 'source_email_reparse'
          else null
        end recommended_action
      from thread_stats s
      join public.commercial_threads t
        on t.organization_id=p_organization_id
       and t.id=s.thread_id
      left join public.conversations c
        on c.organization_id=p_organization_id
       and c.external_thread_id=t.source_conversation_id::text
      left join public.commercial_offer_remediation_queue q
        on q.organization_id=p_organization_id
       and q.thread_id=s.thread_id
      where not exists (
        select 1
        from public.commercial_offer_recoveries r
        where r.organization_id=p_organization_id
          and r.thread_id=s.thread_id
      )
        and s.promoted_count=0
    ),
    eligible as (
      select *
      from classified
      where category is not null
    )
    select jsonb_build_object(
      'summary',jsonb_build_object(
        'blocked_threads',(select count(*) from eligible),
        'direction_conflict',(select count(*) from eligible where category='direction_conflict'),
        'mixed_complete_unique_incomplete',(select count(*) from eligible where category='mixed_complete_unique_incomplete'),
        'product_identity_gap',(select count(*) from eligible where category='product_identity_gap'),
        'source_reparse_required',(select count(*) from eligible where category='source_reparse_required'),
        'queued_pending',(select count(*) from eligible where queue_status='pending'),
        'not_enqueued',(select count(*) from eligible where queue_id is null),
        'price_gap_threads',(select count(*) from eligible where price_gap_count>0),
        'currency_gap_threads',(select count(*) from eligible where currency_gap_count>0),
        'quantity_gap_threads',(select count(*) from eligible where quantity_gap_count>0),
        'threads_with_explicit_missing_field_marker',(
          select count(*) from eligible
          where explicit_price_currency_marker_gap_count>0
             or explicit_quantity_marker_gap_count>0
        )
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'thread_id',e.thread_id,
          'subject',e.subject,
          'source_filename',e.source_filename,
          'source_conversation_id',e.source_conversation_id,
          'conversation_id',e.conversation_id,
          'category',e.category,
          'recommended_action',e.recommended_action,
          'queue_id',e.queue_id,
          'queue_status',e.queue_status,
          'observation_count',e.observation_count,
          'complete_count',e.complete_count,
          'incomplete_count',e.incomplete_count,
          'direction_issue_count',e.direction_issue_count,
          'low_confidence_count',e.low_confidence_count,
          'product_identity_gap_count',e.product_identity_gap_count,
          'quantity_gap_count',e.quantity_gap_count,
          'price_gap_count',e.price_gap_count,
          'currency_gap_count',e.currency_gap_count,
          'explicit_price_currency_marker_gap_count',e.explicit_price_currency_marker_gap_count,
          'explicit_quantity_marker_gap_count',e.explicit_quantity_marker_gap_count,
          'pending_review_count',e.pending_review_count,
          'observations',(
            select coalesce(jsonb_agg(jsonb_build_object(
              'observation_id',o.id,
              'direction',o.direction,
              'confidence',o.confidence,
              'canonical_product_key',o.canonical_product_key,
              'quantity',o.quantity,
              'quantity_unit',o.quantity_unit,
              'price_value',o.price_value,
              'price_unit',o.price_unit,
              'currency',o.currency,
              'source_text',o.source_text,
              'source_clause',o.source_clause
            ) order by o.id),'[]'::jsonb)
            from offered o
            where o.thread_id=e.thread_id
          )
        ) order by
          case e.category
            when 'direction_conflict' then 1
            when 'mixed_complete_unique_incomplete' then 2
            when 'product_identity_gap' then 3
            else 4
          end,
          e.thread_id)
        from (
          select *
          from eligible
          limit greatest(1,least(coalesce(p_limit,100),500))
        ) e
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'pa217_contract_unchanged',true,
        'pa225_contract_unchanged',true,
        'observation_mutation',false,
        'automatic_role_reclassification',false,
        'automatic_direction_correction',false,
        'automatic_price_fill',false,
        'automatic_quantity_fill',false,
        'automatic_product_identity_fill',false,
        'source_reparse_requires_original_source',true,
        'bulk_auto_remediation',false
      )
    )
  );
end;
$$;

revoke all on function public.p1_offer_evidence_remediation_readiness(uuid,integer)
from public,anon;
grant execute on function public.p1_offer_evidence_remediation_readiness(uuid,integer)
to authenticated,service_role;

create or replace function private.enqueue_offer_remediation_impl(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  readiness jsonb;
  candidate jsonb;
  existing public.commercial_offer_remediation_queue%rowtype;
  new_id bigint;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'offer-remediation:'||p_organization_id::text||':'||p_thread_id::text,0));

  select * into existing
  from public.commercial_offer_remediation_queue
  where organization_id=p_organization_id and thread_id=p_thread_id;

  if found then
    return jsonb_build_object(
      'status','already_enqueued',
      'queue_id',existing.id,
      'thread_id',p_thread_id,
      'category',existing.category,
      'recommended_action',existing.recommended_action
    );
  end if;

  readiness := public.p1_offer_evidence_remediation_readiness(p_organization_id,500);

  select x into candidate
  from jsonb_array_elements(readiness->'candidates') x
  where x->>'thread_id'=p_thread_id::text
  limit 1;

  if candidate is null then
    return jsonb_build_object('status','blocked','reason','thread_not_remediation_ready');
  end if;

  insert into public.commercial_offer_remediation_queue(
    organization_id,thread_id,category,recommended_action,status,
    evidence_snapshot,enrolled_by
  ) values (
    p_organization_id,
    p_thread_id,
    candidate->>'category',
    candidate->>'recommended_action',
    'pending',
    candidate,
    actor_id
  )
  returning id into new_id;

  return jsonb_build_object(
    'status','enqueued',
    'queue_id',new_id,
    'thread_id',p_thread_id,
    'category',candidate->>'category',
    'recommended_action',candidate->>'recommended_action',
    'control_phase','PA2.26',
    'execution_mode','single_thread_explicit'
  );
end;
$$;

revoke all on function private.enqueue_offer_remediation_impl(uuid,uuid)
from public,anon;
grant execute on function private.enqueue_offer_remediation_impl(uuid,uuid)
to authenticated,service_role;

create or replace function public.p1_enqueue_offer_remediation_thread(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.enqueue_offer_remediation_impl(p_organization_id,p_thread_id);
$$;

revoke all on function public.p1_enqueue_offer_remediation_thread(uuid,uuid)
from public,anon;
grant execute on function public.p1_enqueue_offer_remediation_thread(uuid,uuid)
to authenticated,service_role;
