-- NC1.2 schema reconciliation: this operational alert table existed in production
-- before its creation was tracked in the versioned migrations.
-- Non-destructive on production; reproducible for fresh Supabase CI database.
create table if not exists public.operational_alerts (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  source_event_id uuid not null references public.observability_events(id) on delete restrict,
  alert_key text not null,
  alert_type text not null,
  severity text not null check (severity in ('warning','critical')),
  status text not null check (status in ('open','acknowledged','resolved')),
  title text not null,
  summary text not null,
  payload jsonb not null default '{}'::jsonb,
  occurrence_count integer not null default 1 check (occurrence_count>=1),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists operational_alerts_one_active_key
  on public.operational_alerts(organization_id, alert_key)
  where status in ('open','acknowledged');
alter table public.operational_alerts enable row level security;
-- The authenticated application uses tenant-scoped security-definer RPCs.
revoke all on public.operational_alerts from public, anon, authenticated;
grant all on public.operational_alerts to service_role;
