create table public.commercial_datasets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  source_run_id uuid not null,
  source_filename text,
  parser_version text,
  email_count integer not null default 0 check (email_count >= 0),
  thread_count integer not null default 0 check (thread_count >= 0),
  message_count integer not null default 0 check (message_count >= 0),
  extraction_count integer not null default 0 check (extraction_count >= 0),
  status text not null default 'ready' check (status in ('ready','active','archived')),
  created_at timestamptz not null default now(),
  unique (owner_id, source_run_id)
);

create table public.commercial_threads (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  dataset_id uuid not null references public.commercial_datasets(id) on delete cascade,
  source_conversation_id uuid not null,
  subject text,
  classification text,
  started_at timestamptz,
  last_activity_at timestamptz,
  email_count integer not null default 0 check (email_count >= 0),
  created_at timestamptz not null default now(),
  unique (owner_id, dataset_id, source_conversation_id)
);

create table public.commercial_observations (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  dataset_id uuid not null references public.commercial_datasets(id) on delete cascade,
  thread_id uuid not null references public.commercial_threads(id) on delete cascade,
  source_extraction_id bigint,
  source_conversation_id uuid not null,
  item_role text not null check (item_role in ('requested','offered','ordered','delivered')),
  role_method text,
  direction text,
  product_type text,
  grade text,
  standard text,
  material_number text,
  outer_diameter_mm numeric,
  width_mm numeric,
  height_mm numeric,
  thickness_mm numeric,
  length_mm numeric,
  quantity numeric,
  quantity_unit text,
  price_value numeric,
  price_unit text,
  currency text,
  discount_percentage numeric,
  availability_status text,
  source_filename text,
  source_text text,
  source_clause text,
  confidence numeric check (confidence is null or (confidence >= 0 and confidence <= 1)),
  flags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.commercial_review_queue (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  dataset_id uuid not null references public.commercial_datasets(id) on delete cascade,
  thread_id uuid not null references public.commercial_threads(id) on delete cascade,
  source_review_id bigint not null,
  source_extraction_ordinal integer,
  reason text not null,
  severity text not null default 'warning' check (severity in ('warning','error')),
  source_text text,
  status text not null default 'pending' check (status in ('pending','confirmed','corrected')),
  corrected_values jsonb,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (owner_id, dataset_id, source_review_id)
);

create index commercial_datasets_owner_status_idx on public.commercial_datasets(owner_id, status);
create index commercial_threads_owner_dataset_idx on public.commercial_threads(owner_id, dataset_id);
create index commercial_threads_owner_activity_idx on public.commercial_threads(owner_id, last_activity_at desc);
create index commercial_observations_owner_role_idx on public.commercial_observations(owner_id, item_role);
create index commercial_observations_owner_grade_idx on public.commercial_observations(owner_id, grade);
create index commercial_observations_owner_standard_idx on public.commercial_observations(owner_id, standard);
create index commercial_observations_owner_dimensions_idx on public.commercial_observations(owner_id, outer_diameter_mm, width_mm, height_mm, thickness_mm);
create index commercial_observations_owner_thread_idx on public.commercial_observations(owner_id, thread_id);
create index commercial_observations_owner_price_idx on public.commercial_observations(owner_id, price_value) where price_value is not null;
create index commercial_review_queue_owner_status_idx on public.commercial_review_queue(owner_id, status);

alter table public.commercial_datasets enable row level security;
alter table public.commercial_threads enable row level security;
alter table public.commercial_observations enable row level security;
alter table public.commercial_review_queue enable row level security;

create policy commercial_datasets_owner_select on public.commercial_datasets
for select to authenticated using ((select auth.uid()) = owner_id);
create policy commercial_threads_owner_select on public.commercial_threads
for select to authenticated using ((select auth.uid()) = owner_id);
create policy commercial_observations_owner_select on public.commercial_observations
for select to authenticated using ((select auth.uid()) = owner_id);
create policy commercial_review_queue_owner_select on public.commercial_review_queue
for select to authenticated using ((select auth.uid()) = owner_id);
create policy commercial_review_queue_owner_update on public.commercial_review_queue
for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

revoke all on table public.commercial_datasets from anon, authenticated;
revoke all on table public.commercial_threads from anon, authenticated;
revoke all on table public.commercial_observations from anon, authenticated;
revoke all on table public.commercial_review_queue from anon, authenticated;
revoke all on sequence public.commercial_observations_id_seq from anon, authenticated;
revoke all on sequence public.commercial_review_queue_id_seq from anon, authenticated;

grant select on table public.commercial_datasets to authenticated;
grant select on table public.commercial_threads to authenticated;
grant select on table public.commercial_observations to authenticated;
grant select on table public.commercial_review_queue to authenticated;
grant update (status, corrected_values, reviewed_at) on table public.commercial_review_queue to authenticated;
