create table if not exists public.market_sources (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  name text not null,
  provider text not null,
  source_url text not null,
  series_type text not null,
  frequency text not null,
  unit text not null,
  geography text,
  category text,
  configuration jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_observations (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.market_sources(id) on delete cascade,
  period date not null,
  value numeric not null,
  unit text not null,
  metadata jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  unique (source_id, period)
);

create index if not exists market_observations_source_period_idx
  on public.market_observations (source_id, period desc);

create table if not exists public.market_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.market_sources(id) on delete cascade,
  status text not null check (status in ('running', 'success', 'failed')),
  observation_count integer not null default 0 check (observation_count >= 0),
  error text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists market_sync_runs_source_started_idx
  on public.market_sync_runs (source_id, started_at desc);

alter table public.market_sources enable row level security;
alter table public.market_observations enable row level security;
alter table public.market_sync_runs enable row level security;

revoke all on table public.market_sources from public, anon, authenticated;
revoke all on table public.market_observations from public, anon, authenticated;
revoke all on table public.market_sync_runs from public, anon, authenticated;
revoke all on sequence public.market_observations_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.market_sources to service_role;
grant select, insert, update, delete on table public.market_observations to service_role;
grant select, insert, update, delete on table public.market_sync_runs to service_role;
grant usage, select on sequence public.market_observations_id_seq to service_role;

insert into public.market_sources (
  key,
  name,
  provider,
  source_url,
  series_type,
  frequency,
  unit,
  geography,
  category,
  configuration
)
values
  (
    'eurostat_it_c242_ppi_domestic',
    'Italia — prezzi alla produzione tubi e profili cavi in acciaio',
    'Eurostat',
    'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/sts_inppd_m',
    'producer_price_index',
    'monthly',
    'I21',
    'IT',
    'NACE C242',
    jsonb_build_object(
      'dataset', 'sts_inppd_m',
      'filters', jsonb_build_object('geo', 'IT', 'nace_r2', 'C242', 'unit', 'I21'),
      'base_year', 2021,
      'display_unit', 'Indice 2021=100'
    )
  ),
  (
    'ecb_eurusd_monthly',
    'EUR/USD — cambio di riferimento mensile',
    'European Central Bank',
    'https://data-api.ecb.europa.eu/service/data/EXR/M.USD.EUR.SP00.A',
    'exchange_rate',
    'monthly',
    'USD_PER_EUR',
    'EUR/USD',
    'ECB reference rate',
    jsonb_build_object(
      'flow', 'EXR',
      'key', 'M.USD.EUR.SP00.A',
      'display_unit', 'USD per EUR'
    )
  )
on conflict (key) do update set
  name = excluded.name,
  provider = excluded.provider,
  source_url = excluded.source_url,
  series_type = excluded.series_type,
  frequency = excluded.frequency,
  unit = excluded.unit,
  geography = excluded.geography,
  category = excluded.category,
  configuration = excluded.configuration,
  updated_at = now();
