-- PA2.27 — Offer Source Reparse Execution Contract.
-- Reparse is source-anchored and candidate-only: no commercial_observations mutation,
-- no automatic promotion, and no remediation resolution.

create table if not exists public.commercial_offer_reparse_runs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  remediation_queue_id bigint not null references public.commercial_offer_remediation_queue(id) on delete restrict,
  thread_id uuid not null references public.commercial_threads(id) on delete restrict,
  source_job_id uuid not null references public.worker_jobs(id) on delete restrict,
  source_storage_path text not null,
  source_checksum text,
  requested_parser_version text not null default 'v4' check (requested_parser_version='v4'),
  status text not null default 'queued' check (status in ('queued','processing','completed','failed')),
  source_snapshot jsonb not null default '{}'::jsonb,
  requested_by uuid not null references auth.users(id) on delete restrict,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  unique (organization_id, remediation_queue_id)
);

create index if not exists commercial_offer_reparse_runs_thread_idx
on public.commercial_offer_reparse_runs(organization_id,thread_id);

create table if not exists public.commercial_offer_reparse_candidates (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  run_id bigint not null references public.commercial_offer_reparse_runs(id) on delete restrict,
  thread_id uuid not null references public.commercial_threads(id) on delete restrict,
  candidate_index integer not null check (candidate_index >= 0),
  source_text text,
  item_role text,
  candidate_evidence jsonb not null,
  comparison_snapshot jsonb not null default '{}'::jsonb,
  review_status text not null default 'pending_review'
    check (review_status in ('pending_review','accepted','rejected')),
  created_at timestamptz not null default now(),
  unique (run_id,candidate_index)
);

create index if not exists commercial_offer_reparse_candidates_thread_idx
on public.commercial_offer_reparse_candidates(organization_id,thread_id);

alter table public.commercial_offer_reparse_runs enable row level security;
alter table public.commercial_offer_reparse_candidates enable row level security;

drop policy if exists "members can read offer reparse runs" on public.commercial_offer_reparse_runs;
create policy "members can read offer reparse runs"
on public.commercial_offer_reparse_runs
for select to authenticated
using (public.is_organization_member(organization_id,false));

drop policy if exists "members can read offer reparse candidates" on public.commercial_offer_reparse_candidates;
create policy "members can read offer reparse candidates"
on public.commercial_offer_reparse_candidates
for select to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on public.commercial_offer_reparse_runs from public,anon,authenticated;
revoke all on public.commercial_offer_reparse_candidates from public,anon,authenticated;
grant select on public.commercial_offer_reparse_runs to authenticated,service_role;
grant select on public.commercial_offer_reparse_candidates to authenticated,service_role;
grant all on public.commercial_offer_reparse_runs to service_role;
grant all on public.commercial_offer_reparse_candidates to service_role;
grant usage,select on sequence public.commercial_offer_reparse_runs_id_seq to service_role;
grant usage,select on sequence public.commercial_offer_reparse_candidates_id_seq to service_role;

create or replace function public.p1_offer_source_reparse_readiness(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with target as (
      select
        q.id remediation_queue_id,
        q.thread_id,
        q.status queue_status,
        t.subject,
        t.dataset_id,
        t.source_conversation_id,
        r.id existing_run_id,
        r.status run_status,
        (
          select w.id
          from public.worker_jobs w
          where w.organization_id=q.organization_id
            and w.storage_path is not null
            and (
              w.thread_id=q.thread_id
              or w.dataset_id=t.dataset_id
              or w.source_thread_id=t.source_conversation_id::text
            )
          order by
            case
              when w.thread_id=q.thread_id then 1
              when w.source_thread_id=t.source_conversation_id::text then 2
              else 3
            end,
            w.completed_at desc nulls last,
            w.created_at desc
          limit 1
        ) source_job_id
      from public.commercial_offer_remediation_queue q
      join public.commercial_threads t
        on t.organization_id=q.organization_id and t.id=q.thread_id
      left join public.commercial_offer_reparse_runs r
        on r.organization_id=q.organization_id and r.remediation_queue_id=q.id
      where q.organization_id=p_organization_id
        and q.category='source_reparse_required'
        and q.recommended_action='source_email_reparse'
        and q.status='pending'
    ),
    enriched as (
      select
        x.*,
        w.filename source_filename,
        w.storage_path,
        w.content_checksum,
        w.parser_version source_parser_version,
        w.status source_job_status,
        case
          when x.source_job_id is null then 'missing_source_job'
          when w.storage_path is null then 'missing_storage_path'
          when w.status is distinct from 'completed' then 'source_job_not_completed'
          when x.existing_run_id is not null then 'already_requested'
          else 'ready'
        end readiness_status
      from target x
      left join public.worker_jobs w on w.id=x.source_job_id
    )
    select jsonb_build_object(
      'summary',jsonb_build_object(
        'target_threads',(select count(*) from enriched),
        'ready',(select count(*) from enriched where readiness_status='ready'),
        'already_requested',(select count(*) from enriched where readiness_status='already_requested'),
        'missing_source_job',(select count(*) from enriched where readiness_status='missing_source_job'),
        'source_job_not_completed',(select count(*) from enriched where readiness_status='source_job_not_completed')
      ),
      'threads',coalesce((
        select jsonb_agg(jsonb_build_object(
          'remediation_queue_id',e.remediation_queue_id,
          'thread_id',e.thread_id,
          'subject',e.subject,
          'source_job_id',e.source_job_id,
          'source_filename',e.source_filename,
          'source_parser_version',e.source_parser_version,
          'source_job_status',e.source_job_status,
          'readiness_status',e.readiness_status,
          'run_id',e.existing_run_id,
          'run_status',e.run_status
        ) order by e.thread_id)
        from (
          select * from enriched
          limit greatest(1,least(coalesce(p_limit,100),500))
        ) e
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'source_is_original_storage_object',true,
        'requested_parser_version','v4',
        'candidate_only',true,
        'observation_mutation',false,
        'automatic_promotion',false,
        'automatic_remediation_resolution',false,
        'single_thread_explicit_execution',true
      )
    )
  );
end;
$$;

revoke all on function public.p1_offer_source_reparse_readiness(uuid,integer) from public,anon;
grant execute on function public.p1_offer_source_reparse_readiness(uuid,integer) to authenticated,service_role;

create or replace function private.request_offer_source_reparse_impl(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  q public.commercial_offer_remediation_queue%rowtype;
  t public.commercial_threads%rowtype;
  w public.worker_jobs%rowtype;
  existing public.commercial_offer_reparse_runs%rowtype;
  new_id bigint;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'offer-source-reparse:'||p_organization_id::text||':'||p_thread_id::text,0));

  select * into q
  from public.commercial_offer_remediation_queue
  where organization_id=p_organization_id
    and thread_id=p_thread_id
    and category='source_reparse_required'
    and recommended_action='source_email_reparse'
    and status='pending';

  if not found then
    return jsonb_build_object('status','blocked','reason','thread_not_source_reparse_ready');
  end if;

  select * into existing
  from public.commercial_offer_reparse_runs
  where organization_id=p_organization_id and remediation_queue_id=q.id;

  if found then
    return jsonb_build_object(
      'status','already_requested','run_id',existing.id,'thread_id',p_thread_id,
      'run_status',existing.status
    );
  end if;

  select * into t
  from public.commercial_threads
  where organization_id=p_organization_id and id=p_thread_id;

  select * into w
  from public.worker_jobs x
  where x.organization_id=p_organization_id
    and x.storage_path is not null
    and (
      x.thread_id=p_thread_id
      or x.dataset_id=t.dataset_id
      or x.source_thread_id=t.source_conversation_id::text
    )
  order by
    case
      when x.thread_id=p_thread_id then 1
      when x.source_thread_id=t.source_conversation_id::text then 2
      else 3
    end,
    x.completed_at desc nulls last,
    x.created_at desc
  limit 1;

  if not found then
    return jsonb_build_object('status','blocked','reason','original_source_job_not_found');
  end if;

  if w.status is distinct from 'completed' or w.storage_path is null then
    return jsonb_build_object('status','blocked','reason','original_source_job_not_materialized');
  end if;

  insert into public.commercial_offer_reparse_runs(
    organization_id,remediation_queue_id,thread_id,source_job_id,
    source_storage_path,source_checksum,requested_parser_version,status,
    source_snapshot,requested_by
  ) values (
    p_organization_id,q.id,p_thread_id,w.id,w.storage_path,w.content_checksum,'v4','queued',
    jsonb_build_object(
      'source_job_id',w.id,
      'filename',w.filename,
      'extension',w.extension,
      'size_bytes',w.size_bytes,
      'storage_path',w.storage_path,
      'content_checksum',w.content_checksum,
      'source_parser_version',w.parser_version,
      'source_thread_id',w.source_thread_id,
      'source_message_id',w.source_message_id
    ),
    actor_id
  ) returning id into new_id;

  return jsonb_build_object(
    'status','queued',
    'run_id',new_id,
    'thread_id',p_thread_id,
    'source_job_id',w.id,
    'requested_parser_version','v4',
    'control_phase','PA2.27',
    'execution_mode','single_thread_explicit',
    'candidate_only',true
  );
end;
$$;

revoke all on function private.request_offer_source_reparse_impl(uuid,uuid) from public,anon;
grant execute on function private.request_offer_source_reparse_impl(uuid,uuid) to authenticated,service_role;

create or replace function public.p1_request_offer_source_reparse(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.request_offer_source_reparse_impl(p_organization_id,p_thread_id);
$$;

revoke all on function public.p1_request_offer_source_reparse(uuid,uuid) from public,anon;
grant execute on function public.p1_request_offer_source_reparse(uuid,uuid) to authenticated,service_role;

create or replace function public.p1_offer_source_reparse_results(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    select jsonb_build_object(
      'run',jsonb_build_object(
        'id',r.id,'thread_id',r.thread_id,'source_job_id',r.source_job_id,
        'requested_parser_version',r.requested_parser_version,'status',r.status,
        'requested_at',r.requested_at,'started_at',r.started_at,
        'completed_at',r.completed_at,'error',r.error
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',c.id,'candidate_index',c.candidate_index,'source_text',c.source_text,
          'item_role',c.item_role,'candidate_evidence',c.candidate_evidence,
          'comparison_snapshot',c.comparison_snapshot,'review_status',c.review_status
        ) order by c.candidate_index)
        from public.commercial_offer_reparse_candidates c
        where c.organization_id=p_organization_id and c.run_id=r.id
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'candidate_only',true,
        'observation_mutation',false,
        'automatic_promotion',false,
        'acceptance_requires_future_controlled_action',true
      )
    )
    from public.commercial_offer_reparse_runs r
    where r.organization_id=p_organization_id and r.thread_id=p_thread_id
    limit 1
  );
end;
$$;

revoke all on function public.p1_offer_source_reparse_results(uuid,uuid) from public,anon;
grant execute on function public.p1_offer_source_reparse_results(uuid,uuid) to authenticated,service_role;
