-- PA2.25 — Relationship Gap Audit & Offer Normalization Recovery.
-- Adds a read-only gap audit plus a narrowly-scoped recovery path for Offer threads
-- where every incomplete offered observation is only a shadow duplicate of a complete priced line.

create table if not exists public.commercial_offer_recoveries (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  thread_id uuid not null references public.commercial_threads(id) on delete restrict,
  offer_id uuid not null references public.offers(id) on delete restrict,
  recovery_type text not null check (recovery_type in ('shadow_duplicate_subset')),
  promoted_observation_ids bigint[] not null,
  retained_evidence_observation_ids bigint[] not null,
  recovered_by uuid not null references auth.users(id) on delete restrict,
  recovered_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (organization_id,thread_id),
  unique (organization_id,offer_id)
);

alter table public.commercial_offer_recoveries enable row level security;

drop policy if exists "members can read commercial offer recoveries"
on public.commercial_offer_recoveries;
create policy "members can read commercial offer recoveries"
on public.commercial_offer_recoveries
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_offer_recoveries from public,anon;
grant select on table public.commercial_offer_recoveries to authenticated,service_role;
grant usage,select on sequence public.commercial_offer_recoveries_id_seq to service_role;

create or replace function public.p1_relationship_gap_offer_recovery_audit(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with rfq as (
      select r.id rfq_id,r.conversation_id,rl.canonical_product_key
      from public.rfqs r
      join public.rfq_lines rl
        on rl.organization_id=r.organization_id and rl.rfq_id=r.id
      where r.organization_id=p_organization_id
    ),
    ord as (
      select o.id order_id,o.conversation_id,ol.canonical_product_key
      from public.orders o
      join public.order_lines ol
        on ol.organization_id=o.organization_id and ol.order_id=o.id
      where o.organization_id=p_organization_id
    ),
    relationship_pairs as (
      select distinct r.conversation_id,r.rfq_id,o.order_id
      from rfq r
      join ord o on o.conversation_id=r.conversation_id
    ),
    relationship_exact_pairs as (
      select distinct r.conversation_id,r.rfq_id,o.order_id
      from rfq r
      join ord o
        on o.conversation_id=r.conversation_id
       and o.canonical_product_key=r.canonical_product_key
    ),
    offered as (
      select
        o.*,
        exists (
          select 1 from public.commercial_review_queue q
          where q.organization_id=o.organization_id
            and q.observation_id=o.id
            and q.status='pending'
        ) pending_review,
        exists (
          select 1 from public.current_commercial_entity_promotions p
          where p.organization_id=o.organization_id
            and p.observation_id=o.id
            and p.entity_type='offer_line'
            and p.status='applied'
        ) already_promoted,
        (
          coalesce(o.confidence,0)>=0.90
          and o.direction='outbound'
          and o.canonical_product_id is not null
          and o.canonical_product_key is not null
          and o.quantity is not null
          and o.quantity_unit is not null
          and o.price_value is not null
          and o.price_unit is not null
          and o.currency is not null
          and nullif(btrim(coalesce(o.source_text,'')),'') is not null
          and not exists (
            select 1 from public.commercial_review_queue q
            where q.organization_id=o.organization_id
              and q.observation_id=o.id
              and q.status='pending'
          )
        ) complete_line
      from public.commercial_observations o
      where o.organization_id=p_organization_id
        and o.item_role='offered'
    ),
    offer_threads as (
      select
        o.thread_id,
        count(*)::int observation_count,
        count(*) filter(where o.complete_line)::int complete_count,
        count(*) filter(where not o.complete_line)::int incomplete_count,
        count(distinct o.currency) filter(where o.complete_line)::int complete_currency_count,
        bool_or(o.pending_review) has_pending_review,
        bool_or(o.already_promoted) has_existing_promotion,
        bool_and(
          o.complete_line
          or (
            coalesce(o.confidence,0)>=0.90
            and o.direction='outbound'
            and o.canonical_product_key is not null
            and nullif(btrim(coalesce(o.source_text,'')),'') is not null
            and not o.pending_review
            and exists (
              select 1
              from offered c
              where c.thread_id=o.thread_id
                and c.complete_line
                and c.canonical_product_key=o.canonical_product_key
                and (
                  o.quantity is null
                  or (
                    o.quantity=c.quantity
                    and o.quantity_unit=c.quantity_unit
                  )
                )
            )
          )
        ) all_incomplete_shadowed,
        count(*) filter(
          where not o.complete_line
            and not exists (
              select 1
              from offered c
              where c.thread_id=o.thread_id
                and c.complete_line
                and c.canonical_product_key=o.canonical_product_key
                and (
                  o.quantity is null
                  or (
                    o.quantity=c.quantity
                    and o.quantity_unit=c.quantity_unit
                  )
                )
            )
        )::int unique_incomplete_count
      from offered o
      group by o.thread_id
    ),
    recovery as (
      select
        t.*,
        ct.subject,
        ct.source_conversation_id,
        c.id conversation_id,
        case
          when exists (
            select 1 from public.commercial_offer_recoveries r
            where r.organization_id=p_organization_id and r.thread_id=t.thread_id
          ) then 'already_recovered'
          when t.has_existing_promotion then 'blocked'
          when t.complete_count=0 then 'blocked'
          when t.complete_currency_count<>1 then 'blocked'
          when t.has_pending_review then 'blocked'
          when c.id is null then 'blocked'
          when not t.all_incomplete_shadowed then 'blocked'
          when t.unique_incomplete_count>0 then 'blocked'
          else 'ready'
        end recovery_status,
        array_remove(array[
          case when t.complete_count=0 then 'no_complete_priced_offer_line' end,
          case when t.complete_currency_count<>1 then 'invalid_complete_currency_set' end,
          case when t.has_pending_review then 'pending_review' end,
          case when t.has_existing_promotion then 'existing_offer_promotion' end,
          case when c.id is null then 'missing_normalized_conversation' end,
          case when not t.all_incomplete_shadowed then 'incomplete_lines_not_all_shadow_duplicates' end,
          case when t.unique_incomplete_count>0 then 'unique_incomplete_product_evidence' end
        ]::text[],null) reasons
      from offer_threads t
      join public.commercial_threads ct
        on ct.organization_id=p_organization_id and ct.id=t.thread_id
      left join public.conversations c
        on c.organization_id=p_organization_id
       and c.external_thread_id=ct.source_conversation_id::text
    )
    select jsonb_build_object(
      'relationship_gap',jsonb_build_object(
        'rfq_total',(select count(distinct rfq_id) from rfq),
        'order_total',(select count(distinct order_id) from ord),
        'shared_conversation_pairs',(select count(*) from relationship_pairs),
        'shared_conversation_exact_product_pairs',(select count(*) from relationship_exact_pairs),
        'normalized_offer_total',(select count(*) from public.offers where organization_id=p_organization_id)
      ),
      'offer_gap',jsonb_build_object(
        'offered_observations',(select count(*) from offered),
        'offer_threads',(select count(*) from offer_threads),
        'complete_observations',(select count(*) from offered where complete_line),
        'threads_with_any_complete_line',(select count(*) from offer_threads where complete_count>0),
        'safe_subset_recovery_ready',(select count(*) from recovery where recovery_status='ready'),
        'already_recovered',(select count(*) from recovery where recovery_status='already_recovered'),
        'blocked_recovery_threads',(select count(*) from recovery where recovery_status='blocked')
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'thread_id',r.thread_id,
          'subject',r.subject,
          'conversation_id',r.conversation_id,
          'source_conversation_id',r.source_conversation_id,
          'recovery_status',r.recovery_status,
          'reasons',to_jsonb(r.reasons),
          'observation_count',r.observation_count,
          'complete_count',r.complete_count,
          'incomplete_count',r.incomplete_count,
          'unique_incomplete_count',r.unique_incomplete_count,
          'complete_lines',(
            select coalesce(jsonb_agg(jsonb_build_object(
              'observation_id',o.id,
              'canonical_product_key',o.canonical_product_key,
              'quantity',o.quantity,
              'quantity_unit',o.quantity_unit,
              'price_value',o.price_value,
              'price_unit',o.price_unit,
              'currency',o.currency,
              'source_text',o.source_text
            ) order by o.id),'[]'::jsonb)
            from offered o
            where o.thread_id=r.thread_id and o.complete_line
          ),
          'retained_evidence_lines',(
            select coalesce(jsonb_agg(jsonb_build_object(
              'observation_id',o.id,
              'canonical_product_key',o.canonical_product_key,
              'quantity',o.quantity,
              'quantity_unit',o.quantity_unit,
              'source_text',o.source_text
            ) order by o.id),'[]'::jsonb)
            from offered o
            where o.thread_id=r.thread_id and not o.complete_line
          )
        ) order by case r.recovery_status when 'ready' then 0 when 'blocked' then 1 else 2 end,r.thread_id)
        from (
          select * from recovery
          limit greatest(1,least(coalesce(p_limit,100),500))
        ) r
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'pa217_contract_unchanged',true,
        'recovery_type','shadow_duplicate_subset',
        'requires_at_least_one_complete_priced_line',true,
        'requires_every_incomplete_line_shadowed',true,
        'requires_no_unique_incomplete_products',true,
        'requires_single_currency',true,
        'requires_normalized_conversation',true,
        'company_inference',false,
        'rfq_inference',false,
        'bulk_auto_recovery',false
      )
    )
  );
end;
$$;

revoke all on function public.p1_relationship_gap_offer_recovery_audit(uuid,integer) from public,anon;
grant execute on function public.p1_relationship_gap_offer_recovery_audit(uuid,integer) to authenticated,service_role;

create or replace function private.recover_shadow_duplicate_offer_impl(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  target_thread public.commercial_threads%rowtype;
  conversation_id uuid;
  new_offer_id uuid := gen_random_uuid();
  new_line_id uuid;
  offer_currency text;
  offered_at timestamptz;
  complete_count int;
  incomplete_count int;
  unique_incomplete_count int;
  currency_count int;
  has_pending boolean;
  has_existing_promotion boolean;
  all_shadowed boolean;
  obs public.commercial_observations%rowtype;
  promotion_id bigint;
  promoted_ids bigint[] := '{}'::bigint[];
  retained_ids bigint[] := '{}'::bigint[];
  line_results jsonb := '[]'::jsonb;
  recovery_id bigint;
  existing_recovery public.commercial_offer_recoveries%rowtype;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'offer-recovery:'||p_organization_id::text||':'||p_thread_id::text,0));

  select * into target_thread
  from public.commercial_threads
  where organization_id=p_organization_id and id=p_thread_id;

  if not found then raise exception 'Commercial thread not found in organization'; end if;

  select * into existing_recovery
  from public.commercial_offer_recoveries
  where organization_id=p_organization_id and thread_id=p_thread_id;

  if found then
    return jsonb_build_object(
      'status','already_recovered',
      'recovery_id',existing_recovery.id,
      'offer_id',existing_recovery.offer_id,
      'thread_id',p_thread_id
    );
  end if;

  select c.id into conversation_id
  from public.conversations c
  where c.organization_id=p_organization_id
    and c.external_thread_id=target_thread.source_conversation_id::text
  limit 1;

  with offered as (
    select
      o.*,
      exists (
        select 1 from public.commercial_review_queue q
        where q.organization_id=o.organization_id
          and q.observation_id=o.id
          and q.status='pending'
      ) pending_review,
      exists (
        select 1 from public.current_commercial_entity_promotions p
        where p.organization_id=o.organization_id
          and p.observation_id=o.id
          and p.entity_type='offer_line'
          and p.status='applied'
      ) already_promoted,
      (
        coalesce(o.confidence,0)>=0.90
        and o.direction='outbound'
        and o.canonical_product_id is not null
        and o.canonical_product_key is not null
        and o.quantity is not null and o.quantity_unit is not null
        and o.price_value is not null and o.price_unit is not null
        and o.currency is not null
        and nullif(btrim(coalesce(o.source_text,'')),'') is not null
        and not exists (
          select 1 from public.commercial_review_queue q
          where q.organization_id=o.organization_id
            and q.observation_id=o.id
            and q.status='pending'
        )
      ) complete_line
    from public.commercial_observations o
    where o.organization_id=p_organization_id
      and o.thread_id=p_thread_id
      and o.item_role='offered'
  )
  select
    count(*) filter(where complete_line)::int,
    count(*) filter(where not complete_line)::int,
    count(distinct currency) filter(where complete_line)::int,
    bool_or(pending_review),
    bool_or(already_promoted),
    bool_and(
      complete_line
      or (
        coalesce(confidence,0)>=0.90
        and direction='outbound'
        and canonical_product_key is not null
        and nullif(btrim(coalesce(source_text,'')),'') is not null
        and not pending_review
        and exists (
          select 1 from offered c
          where c.complete_line
            and c.canonical_product_key=offered.canonical_product_key
            and (
              offered.quantity is null
              or (
                offered.quantity=c.quantity
                and offered.quantity_unit=c.quantity_unit
              )
            )
        )
      )
    ),
    count(*) filter(
      where not complete_line
        and not exists (
          select 1 from offered c
          where c.complete_line
            and c.canonical_product_key=offered.canonical_product_key
            and (
              offered.quantity is null
              or (
                offered.quantity=c.quantity
                and offered.quantity_unit=c.quantity_unit
              )
            )
        )
    )::int,
    min(currency) filter(where complete_line),
    min(created_at) filter(where complete_line)
  into complete_count,incomplete_count,currency_count,has_pending,has_existing_promotion,
       all_shadowed,unique_incomplete_count,offer_currency,offered_at
  from offered;

  if complete_count=0
     or currency_count<>1
     or coalesce(has_pending,false)
     or coalesce(has_existing_promotion,false)
     or conversation_id is null
     or not coalesce(all_shadowed,false)
     or unique_incomplete_count>0 then
    return jsonb_build_object(
      'status','blocked',
      'thread_id',p_thread_id,
      'complete_count',complete_count,
      'incomplete_count',incomplete_count,
      'currency_count',currency_count,
      'has_pending_review',coalesce(has_pending,false),
      'has_existing_promotion',coalesce(has_existing_promotion,false),
      'has_normalized_conversation',conversation_id is not null,
      'all_incomplete_shadowed',coalesce(all_shadowed,false),
      'unique_incomplete_count',unique_incomplete_count
    );
  end if;

  insert into public.offers(
    id,owner_id,organization_id,created_by_user_id,assigned_to_user_id,
    conversation_id,offered_at,status,currency,notes
  ) values (
    new_offer_id,actor_id,p_organization_id,actor_id,actor_id,
    conversation_id,offered_at,'sent',offer_currency,
    concat('PA2.25 shadow-duplicate subset recovery from commercial thread ',p_thread_id,
           '. Incomplete duplicate evidence retained and not promoted. Company/RFQ unresolved.')
  );

  for obs in
    select o.*
    from public.commercial_observations o
    where o.organization_id=p_organization_id
      and o.thread_id=p_thread_id
      and o.item_role='offered'
      and coalesce(o.confidence,0)>=0.90
      and o.direction='outbound'
      and o.canonical_product_id is not null
      and o.canonical_product_key is not null
      and o.quantity is not null
      and o.quantity_unit is not null
      and o.price_value is not null
      and o.price_unit is not null
      and o.currency is not null
      and nullif(btrim(coalesce(o.source_text,'')),'') is not null
      and not exists (
        select 1 from public.commercial_review_queue q
        where q.organization_id=o.organization_id
          and q.observation_id=o.id
          and q.status='pending'
      )
    order by o.id
  loop
    new_line_id := gen_random_uuid();

    insert into public.offer_lines(
      id,owner_id,organization_id,offer_id,
      quantity,quantity_unit,price_value,price_unit,
      source_text,confidence,canonical_product_id,canonical_product_key,
      source_observation_id,raw_spec_text
    ) values (
      new_line_id,actor_id,p_organization_id,new_offer_id,
      obs.quantity,obs.quantity_unit,obs.price_value,obs.price_unit,
      obs.source_text,obs.confidence,obs.canonical_product_id,obs.canonical_product_key,
      obs.id,obs.source_text
    );

    promotion_id := private.record_commercial_entity_promotion_impl(
      p_organization_id,obs.id,'offer_line',new_line_id,
      null,'created','applied',obs.confidence,'deterministic_match',
      null,null,jsonb_build_object(
        'phase','PA2.25',
        'service','shadow_duplicate_subset_offer_recovery',
        'thread_id',p_thread_id,
        'company_inference',false,
        'rfq_inference',false
      )
    );

    promoted_ids := array_append(promoted_ids,obs.id);
    line_results := line_results || jsonb_build_array(jsonb_build_object(
      'observation_id',obs.id,
      'offer_line_id',new_line_id,
      'promotion_id',promotion_id
    ));
  end loop;

  select coalesce(array_agg(o.id order by o.id),'{}'::bigint[])
  into retained_ids
  from public.commercial_observations o
  where o.organization_id=p_organization_id
    and o.thread_id=p_thread_id
    and o.item_role='offered'
    and not (o.id=any(promoted_ids));

  insert into public.commercial_offer_recoveries(
    organization_id,thread_id,offer_id,recovery_type,
    promoted_observation_ids,retained_evidence_observation_ids,
    recovered_by,metadata
  ) values (
    p_organization_id,p_thread_id,new_offer_id,'shadow_duplicate_subset',
    promoted_ids,retained_ids,actor_id,
    jsonb_build_object(
      'phase','PA2.25',
      'complete_count',complete_count,
      'retained_evidence_count',incomplete_count,
      'conversation_id',conversation_id,
      'company_inference',false,
      'rfq_inference',false,
      'execution_mode','single_thread_explicit'
    )
  )
  returning id into recovery_id;

  return jsonb_build_object(
    'status','recovered',
    'recovery_id',recovery_id,
    'thread_id',p_thread_id,
    'offer_id',new_offer_id,
    'conversation_id',conversation_id,
    'promoted_observation_ids',to_jsonb(promoted_ids),
    'retained_evidence_observation_ids',to_jsonb(retained_ids),
    'lines',line_results,
    'control_phase','PA2.25',
    'execution_mode','single_thread_explicit'
  );
end;
$$;

revoke all on function private.recover_shadow_duplicate_offer_impl(uuid,uuid) from public,anon;
grant execute on function private.recover_shadow_duplicate_offer_impl(uuid,uuid) to authenticated,service_role;

create or replace function public.p1_recover_shadow_duplicate_offer(
  p_organization_id uuid,
  p_thread_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.recover_shadow_duplicate_offer_impl(p_organization_id,p_thread_id);
$$;

revoke all on function public.p1_recover_shadow_duplicate_offer(uuid,uuid) from public,anon;
grant execute on function public.p1_recover_shadow_duplicate_offer(uuid,uuid) to authenticated,service_role;
