create table public.commercial_message_identity_recoveries (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  conversation_id uuid not null,
  message_id uuid not null,
  source_kind text not null,
  source_filename text not null,
  source_content_hash text not null,
  sender_email_normalized text not null,
  sender_name text,
  direction text not null,
  sent_at timestamptz,
  subject text,
  recovered_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint commercial_message_identity_recoveries_org_conversation_fkey
    foreign key (organization_id,conversation_id)
    references public.conversations(organization_id,id),
  constraint commercial_message_identity_recoveries_org_message_fkey
    foreign key (organization_id,message_id)
    references public.messages(organization_id,id),
  constraint commercial_message_identity_recoveries_source_uq
    unique (organization_id,source_kind,source_content_hash),
  constraint commercial_message_identity_recoveries_source_kind_check
    check (source_kind in ('legacy_messages_v31')),
  constraint commercial_message_identity_recoveries_direction_check
    check (direction in ('inbound','outbound')),
  constraint commercial_message_identity_recoveries_hash_check
    check (source_content_hash ~ '^[0-9a-f]{64}$')
);

alter table public.commercial_message_identity_recoveries enable row level security;

create policy commercial_message_identity_recoveries_select_member
on public.commercial_message_identity_recoveries
for select to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_message_identity_recoveries from public,anon;
grant select on table public.commercial_message_identity_recoveries to authenticated,service_role;

create or replace function private.resolve_message_business_identity_impl(p_message_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := (select auth.uid());
  target_message public.messages%rowtype;
  target_contact public.contacts%rowtype;
  normalized_sender text;
  identity_message_count integer := 0;
  exact_contact_message_count integer := 0;
  mapped_company_message_count integer := 0;
  distinct_contact_count integer := 0;
  distinct_company_count integer := 0;
  consensus_contact_id uuid;
  consensus_company_id uuid;
  rfq_linked_count integer := 0;
  contact_consensus boolean := false;
  company_consensus boolean := false;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into target_message
  from public.messages
  where id=p_message_id
  for update;

  if not found then
    raise exception 'Message not found';
  end if;

  if not public.is_organization_member(target_message.organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  normalized_sender := lower(btrim(coalesce(target_message.sender_email,'')));

  if normalized_sender='' then
    return jsonb_build_object(
      'status','blocked_missing_sender_email',
      'message_id',target_message.id
    );
  end if;

  select *
  into target_contact
  from public.contacts c
  where c.organization_id=target_message.organization_id
    and c.email_normalized=normalized_sender
  limit 1;

  if not found then
    return jsonb_build_object(
      'status','blocked_missing_verified_contact',
      'message_id',target_message.id,
      'sender_email',normalized_sender
    );
  end if;

  update public.messages
  set
    sender_contact_id=target_contact.id,
    sender_company_id=target_contact.company_id
  where id=target_message.id;

  insert into public.commercial_identity_resolutions(
    organization_id,message_id,contact_id,company_id,resolution_type,basis,resolved_by,metadata
  )
  values(
    target_message.organization_id,
    target_message.id,
    target_contact.id,
    null,
    'contact',
    'exact_email',
    actor_id,
    jsonb_build_object('sender_email',normalized_sender)
  )
  on conflict do nothing;

  if target_contact.company_id is not null then
    insert into public.commercial_identity_resolutions(
      organization_id,message_id,contact_id,company_id,resolution_type,basis,resolved_by,metadata
    )
    values(
      target_message.organization_id,
      target_message.id,
      target_contact.id,
      target_contact.company_id,
      'contact_company',
      'verified_contact_company',
      actor_id,
      jsonb_build_object('contact_id',target_contact.id)
    )
    on conflict do nothing;
  end if;

  if target_message.conversation_id is not null then
    select
      count(*)::int,
      count(c.id)::int,
      count(c.company_id)::int,
      count(distinct c.id)::int,
      count(distinct c.company_id)::int,
      min(c.id::text)::uuid,
      min(c.company_id::text)::uuid
    into
      identity_message_count,
      exact_contact_message_count,
      mapped_company_message_count,
      distinct_contact_count,
      distinct_company_count,
      consensus_contact_id,
      consensus_company_id
    from public.messages m
    left join public.contacts c
      on c.organization_id=m.organization_id
     and c.email_normalized=lower(btrim(coalesce(m.sender_email,'')))
    where m.organization_id=target_message.organization_id
      and m.conversation_id=target_message.conversation_id
      and coalesce(m.direction,'inbound')<>'outbound'
      and nullif(lower(btrim(coalesce(m.sender_email,''))),'') is not null;

    contact_consensus :=
      identity_message_count>0
      and exact_contact_message_count=identity_message_count
      and distinct_contact_count=1;

    company_consensus :=
      identity_message_count>0
      and mapped_company_message_count=identity_message_count
      and distinct_company_count=1;

    with target_rfqs as (
      select r.id
      from public.rfqs r
      where r.organization_id=target_message.organization_id
        and r.conversation_id=target_message.conversation_id

      union

      select distinct r.id
      from public.conversations c
      join public.commercial_threads t
        on t.organization_id=c.organization_id
       and t.source_conversation_id::text=c.external_thread_id
      join public.commercial_observations o
        on o.organization_id=t.organization_id
       and o.thread_id=t.id
      join public.current_commercial_entity_promotions p
        on p.organization_id=o.organization_id
       and p.observation_id=o.id
       and p.entity_type='rfq_line'
      join public.rfq_lines rl
        on rl.organization_id=p.organization_id
       and rl.id=p.entity_id
      join public.rfqs r
        on r.organization_id=rl.organization_id
       and r.id=rl.rfq_id
      where c.organization_id=target_message.organization_id
        and c.id=target_message.conversation_id
    )
    update public.rfqs r
    set
      source_message_id=case
        when identity_message_count=1 then coalesce(r.source_message_id,target_message.id)
        else r.source_message_id
      end,
      contact_id=case
        when contact_consensus then coalesce(r.contact_id,consensus_contact_id)
        else r.contact_id
      end,
      company_id=case
        when company_consensus then coalesce(r.company_id,consensus_company_id)
        else r.company_id
      end
    where r.organization_id=target_message.organization_id
      and r.id in (select id from target_rfqs)
      and (identity_message_count<>1 or r.source_message_id is null or r.source_message_id=target_message.id)
      and (not contact_consensus or r.contact_id is null or r.contact_id=consensus_contact_id)
      and (not company_consensus or r.company_id is null or r.company_id=consensus_company_id)
      and (
        (identity_message_count=1 and r.source_message_id is null)
        or (contact_consensus and r.contact_id is null)
        or (company_consensus and r.company_id is null)
      );

    get diagnostics rfq_linked_count=row_count;
  end if;

  return jsonb_build_object(
    'status','resolved',
    'message_id',target_message.id,
    'contact_id',target_contact.id,
    'company_id',target_contact.company_id,
    'company_status',case
      when target_contact.company_id is null then 'blocked_missing_verified_company_mapping'
      when company_consensus then 'linked_verified_company_consensus'
      else 'blocked_conversation_company_consensus'
    end,
    'conversation_identity',jsonb_build_object(
      'identity_message_count',identity_message_count,
      'exact_contact_message_count',exact_contact_message_count,
      'mapped_company_message_count',mapped_company_message_count,
      'distinct_contact_count',distinct_contact_count,
      'distinct_company_count',distinct_company_count,
      'contact_consensus',contact_consensus,
      'company_consensus',company_consensus,
      'consensus_contact_id',consensus_contact_id,
      'consensus_company_id',consensus_company_id
    ),
    'rfq_linked_count',rfq_linked_count
  );
end;
$$;

create or replace function private.p2_recover_legacy_message_identity_impl(
  p_organization_id uuid,
  p_conversation_id uuid,
  p_source_filename text,
  p_source_content_hash text,
  p_sender_email text,
  p_sender_name text,
  p_direction text,
  p_sent_at timestamptz,
  p_subject text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := (select auth.uid());
  target_conversation public.conversations%rowtype;
  normalized_email text := lower(btrim(coalesce(p_sender_email,'')));
  normalized_name text := nullif(btrim(coalesce(p_sender_name,'')),'');
  normalized_direction text := lower(btrim(coalesce(p_direction,'')));
  normalized_hash text := lower(btrim(coalesce(p_source_content_hash,'')));
  target_message public.messages%rowtype;
  contact_result jsonb;
  materialization_status text;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  if normalized_email='' or position('@' in normalized_email)<=1 then
    raise exception 'Valid sender email required';
  end if;

  if normalized_name is null then
    raise exception 'Sender name required';
  end if;

  if normalized_direction not in ('inbound','outbound') then
    raise exception 'Direction must be inbound or outbound';
  end if;

  if normalized_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Valid SHA-256 content hash required';
  end if;

  select *
  into target_conversation
  from public.conversations c
  where c.organization_id=p_organization_id
    and c.id=p_conversation_id
  for share;

  if not found then
    raise exception 'Conversation not found in organization';
  end if;

  contact_result := private.upsert_verified_contact_identity_impl(
    p_organization_id,
    normalized_email,
    normalized_name,
    null
  );

  select *
  into target_message
  from public.messages m
  where m.organization_id=p_organization_id
    and m.external_message_id='legacy:v31:'||normalized_hash
  limit 1;

  if not found then
    insert into public.messages(
      owner_id,organization_id,conversation_id,external_message_id,source_thread_id,
      direction,sender_email,recipient_emails,sent_at,subject
    )
    values(
      actor_id,
      p_organization_id,
      target_conversation.id,
      'legacy:v31:'||normalized_hash,
      target_conversation.external_thread_id,
      normalized_direction,
      normalized_email,
      '{}'::text[],
      p_sent_at,
      nullif(btrim(coalesce(p_subject,'')),'')
    )
    returning * into target_message;

    materialization_status := 'materialized';
  else
    if target_message.conversation_id<>target_conversation.id
       or lower(btrim(coalesce(target_message.sender_email,'')))<>normalized_email then
      raise exception 'Legacy source hash conflicts with existing message identity';
    end if;
    materialization_status := 'existing';
  end if;

  insert into public.commercial_message_identity_recoveries(
    organization_id,conversation_id,message_id,source_kind,source_filename,
    source_content_hash,sender_email_normalized,sender_name,direction,sent_at,subject,recovered_by
  )
  values(
    p_organization_id,
    target_conversation.id,
    target_message.id,
    'legacy_messages_v31',
    btrim(p_source_filename),
    normalized_hash,
    normalized_email,
    normalized_name,
    normalized_direction,
    p_sent_at,
    nullif(btrim(coalesce(p_subject,'')),''),
    actor_id
  )
  on conflict (organization_id,source_kind,source_content_hash) do nothing;

  return jsonb_build_object(
    'status',materialization_status,
    'conversation_id',target_conversation.id,
    'message_id',target_message.id,
    'contact',contact_result,
    'source_kind','legacy_messages_v31',
    'source_content_hash',normalized_hash,
    'finalization_required',true
  );
end;
$$;

create or replace function private.p2_finalize_legacy_conversation_identity_impl(
  p_organization_id uuid,
  p_conversation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := (select auth.uid());
  target_message record;
  resolution_result jsonb;
  resolved_messages integer := 0;
  linked_rfqs integer := 0;
  final_company_id uuid;
  final_contact_id uuid;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  if not exists (
    select 1
    from public.conversations c
    where c.organization_id=p_organization_id
      and c.id=p_conversation_id
  ) then
    raise exception 'Conversation not found in organization';
  end if;

  for target_message in
    select m.id
    from public.messages m
    join public.commercial_message_identity_recoveries r
      on r.organization_id=m.organization_id
     and r.message_id=m.id
     and r.source_kind='legacy_messages_v31'
    where m.organization_id=p_organization_id
      and m.conversation_id=p_conversation_id
    order by m.sent_at nulls last,m.id
  loop
    resolution_result := private.resolve_message_business_identity_impl(target_message.id);

    if resolution_result->>'status'='resolved' then
      resolved_messages := resolved_messages+1;
      linked_rfqs := linked_rfqs+coalesce((resolution_result->>'rfq_linked_count')::int,0);
    end if;
  end loop;

  select
    min(r.company_id::text)::uuid,
    min(r.contact_id::text)::uuid
  into final_company_id,final_contact_id
  from public.rfqs r
  where r.organization_id=p_organization_id
    and r.conversation_id=p_conversation_id;

  return jsonb_build_object(
    'status','finalized',
    'conversation_id',p_conversation_id,
    'resolved_messages',resolved_messages,
    'linked_rfqs',linked_rfqs,
    'company_id',final_company_id,
    'contact_id',final_contact_id
  );
end;
$$;

create or replace function public.p2_recover_legacy_message_identity(
  p_organization_id uuid,
  p_conversation_id uuid,
  p_source_filename text,
  p_source_content_hash text,
  p_sender_email text,
  p_sender_name text,
  p_direction text,
  p_sent_at timestamptz,
  p_subject text
)
returns jsonb
language sql
set search_path = ''
as $$
  select private.p2_recover_legacy_message_identity_impl(
    p_organization_id,p_conversation_id,p_source_filename,p_source_content_hash,
    p_sender_email,p_sender_name,p_direction,p_sent_at,p_subject
  );
$$;

create or replace function public.p2_finalize_legacy_conversation_identity(
  p_organization_id uuid,
  p_conversation_id uuid
)
returns jsonb
language sql
set search_path = ''
as $$
  select private.p2_finalize_legacy_conversation_identity_impl(
    p_organization_id,p_conversation_id
  );
$$;

revoke all on function public.p2_recover_legacy_message_identity(
  uuid,uuid,text,text,text,text,text,timestamptz,text
) from public,anon;
revoke all on function public.p2_finalize_legacy_conversation_identity(uuid,uuid)
  from public,anon;

grant execute on function public.p2_recover_legacy_message_identity(
  uuid,uuid,text,text,text,text,text,timestamptz,text
) to authenticated,service_role;
grant execute on function public.p2_finalize_legacy_conversation_identity(uuid,uuid)
  to authenticated,service_role;

create or replace function public.p2_rfq_attribution_recovery_status(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
with access_check as (
  select public.is_organization_member(p_organization_id,false) as allowed
),
recovery_summary as (
  select
    count(*)::int as recovered_messages,
    count(distinct conversation_id)::int as recovered_conversations
  from public.commercial_message_identity_recoveries
  where organization_id=p_organization_id
    and (select allowed from access_check)
),
unresolved as (
  select
    r.id as rfq_id,
    r.conversation_id,
    c.subject,
    c.external_thread_id,
    r.contact_id,
    r.company_id,
    count(m.id)::int as identity_message_count,
    count(distinct m.sender_contact_id)
      filter(where m.sender_contact_id is not null)::int as distinct_contact_count,
    count(distinct m.sender_company_id)
      filter(where m.sender_company_id is not null)::int as distinct_company_count,
    array_remove(
      array_agg(distinct nullif(lower(btrim(m.sender_email)),'')),
      null
    ) as sender_emails,
    max(ct.full_name) filter(where ct.id=r.contact_id) as contact_name
  from public.rfqs r
  join public.conversations c
    on c.organization_id=r.organization_id
   and c.id=r.conversation_id
  left join public.messages m
    on m.organization_id=r.organization_id
   and m.conversation_id=r.conversation_id
   and coalesce(m.direction,'inbound')<>'outbound'
  left join public.contacts ct
    on ct.organization_id=r.organization_id
   and ct.id=r.contact_id
  where r.organization_id=p_organization_id
    and r.company_id is null
    and (select allowed from access_check)
  group by
    r.id,r.conversation_id,c.subject,c.external_thread_id,r.contact_id,r.company_id
),
classified as (
  select
    u.*,
    case
      when u.identity_message_count=0 then 'missing_legacy_message'
      when u.distinct_contact_count>1 or u.distinct_company_count>1 then 'blocked_identity_conflict'
      when u.contact_id is not null and u.distinct_company_count=0 then 'pending_company_confirmation'
      when u.contact_id is null then 'pending_contact_resolution'
      else 'unresolved'
    end as recovery_status
  from unresolved u
),
rows as (
  select *
  from classified
  order by
    case recovery_status
      when 'pending_company_confirmation' then 0
      when 'pending_contact_resolution' then 1
      when 'missing_legacy_message' then 2
      else 3
    end,
    subject,
    rfq_id
  limit greatest(1,least(coalesce(p_limit,100),500))
)
select jsonb_build_object(
  'summary',jsonb_build_object(
    'recovered_messages',(select recovered_messages from recovery_summary),
    'recovered_conversations',(select recovered_conversations from recovery_summary),
    'unattributed_rfqs',(select count(*) from classified),
    'missing_legacy_message',(select count(*) from classified where recovery_status='missing_legacy_message'),
    'pending_company_confirmation',(select count(*) from classified where recovery_status='pending_company_confirmation'),
    'pending_contact_resolution',(select count(*) from classified where recovery_status='pending_contact_resolution'),
    'blocked_identity_conflict',(select count(*) from classified where recovery_status='blocked_identity_conflict')
  ),
  'rfqs',coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'rfq_id',rfq_id,
        'conversation_id',conversation_id,
        'subject',subject,
        'external_thread_id',external_thread_id,
        'contact_id',contact_id,
        'contact_name',contact_name,
        'identity_message_count',identity_message_count,
        'sender_emails',to_jsonb(sender_emails),
        'recovery_status',recovery_status
      )
      order by
        case recovery_status
          when 'pending_company_confirmation' then 0
          when 'pending_contact_resolution' then 1
          when 'missing_legacy_message' then 2
          else 3
        end,
        subject,
        rfq_id
    )
    from rows
  ),'[]'::jsonb),
  'policy',jsonb_build_object(
    'exact_header_only',true,
    'email_domain_inference',false,
    'filename_inference',false,
    'subject_inference',false,
    'body_inference',false,
    'company_requires_verified_contact_mapping',true,
    'multi_message_company_requires_consensus',true,
    'materialize_then_finalize',true
  )
);
$$;

revoke all on function public.p2_rfq_attribution_recovery_status(uuid,integer)
  from public,anon;
grant execute on function public.p2_rfq_attribution_recovery_status(uuid,integer)
  to authenticated,service_role;

comment on table public.commercial_message_identity_recoveries is
  'P2.3 audit ledger for deterministic message identity recovered from structured legacy parser output.';

comment on function public.p2_recover_legacy_message_identity(
  uuid,uuid,text,text,text,text,text,timestamptz,text
) is
  'P2.3 materializes an exact legacy message header and Contact without inferring Company. Finalize the conversation separately.';

comment on function public.p2_finalize_legacy_conversation_identity(uuid,uuid) is
  'P2.3 finalizes recovered conversation identity only after all legacy headers are materialized; multi-message Company propagation requires consensus.';

comment on function public.p2_rfq_attribution_recovery_status(uuid,integer) is
  'P2.3 tenant-safe read model for remaining RFQ attribution recovery and manual Company confirmation.';
