-- PA2.22 — Conversation Relationship Backfill Readiness.
-- Controlled linking of normalized RFQ / Offer / Order entities to normalized Conversations.
-- Only structured identities are accepted: source_message_id -> messages.conversation_id,
-- or source observation source_conversation_id -> conversations.external_thread_id.
-- No subject/name/domain/free-text/thread-similarity inference.

create table if not exists public.commercial_conversation_backfills (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  entity_type text not null check (entity_type in ('rfq','offer','order')),
  entity_id uuid not null,
  conversation_id uuid not null,
  evidence_type text not null check (evidence_type in ('source_message','source_conversation_id')),
  status text not null check (status in ('applied')),
  activated_by uuid not null references auth.users(id) on delete restrict,
  activated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (organization_id,entity_type,entity_id)
);

alter table public.commercial_conversation_backfills enable row level security;

drop policy if exists "members can read commercial conversation backfills"
on public.commercial_conversation_backfills;
create policy "members can read commercial conversation backfills"
on public.commercial_conversation_backfills
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_conversation_backfills from public,anon;
grant select on table public.commercial_conversation_backfills to authenticated,service_role;
grant usage,select on sequence public.commercial_conversation_backfills_id_seq to service_role;

create or replace function public.p1_conversation_backfill_readiness(
  p_organization_id uuid,
  p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security invoker
set search_path=''
as $$
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  return (
    with entities as (
      select 'rfq'::text entity_type,r.id entity_id,r.conversation_id,r.source_message_id,
             rl.source_observation_id
      from public.rfqs r
      join public.rfq_lines rl
        on rl.organization_id=r.organization_id and rl.rfq_id=r.id
      where r.organization_id=p_organization_id

      union all

      select 'offer',o.id,o.conversation_id,o.source_message_id,ol.source_observation_id
      from public.offers o
      join public.offer_lines ol
        on ol.organization_id=o.organization_id and ol.offer_id=o.id
      where o.organization_id=p_organization_id

      union all

      select 'order',o.id,o.conversation_id,o.source_message_id,ol.source_observation_id
      from public.orders o
      join public.order_lines ol
        on ol.organization_id=o.organization_id and ol.order_id=o.id
      where o.organization_id=p_organization_id
    ),
    evidence as (
      select
        e.*,
        m.conversation_id message_conversation_id,
        c.id source_conversation_match
      from entities e
      left join public.messages m
        on m.organization_id=p_organization_id
       and m.id=e.source_message_id
      left join public.commercial_observations obs
        on obs.organization_id=p_organization_id
       and obs.id=e.source_observation_id
      left join public.conversations c
        on c.organization_id=p_organization_id
       and c.external_thread_id=obs.source_conversation_id::text
       and obs.source_conversation_id is not null
    ),
    grouped as (
      select
        entity_type,
        entity_id,
        min(conversation_id::text)::uuid existing_conversation_id,
        count(*) line_count,
        count(distinct message_conversation_id) filter(where message_conversation_id is not null) message_candidate_count,
        min(message_conversation_id::text) filter(where message_conversation_id is not null)::uuid message_candidate_id,
        count(distinct source_conversation_match) filter(where source_conversation_match is not null) source_candidate_count,
        min(source_conversation_match::text) filter(where source_conversation_match is not null)::uuid source_candidate_id
      from evidence
      group by entity_type,entity_id
    ),
    classified as (
      select
        g.*,
        case
          when existing_conversation_id is not null then 'already_linked'
          when message_candidate_count=1
               and source_candidate_count in (0,1)
               and (source_candidate_count=0 or source_candidate_id=message_candidate_id)
            then 'ready'
          when message_candidate_count=0 and source_candidate_count=1
            then 'ready'
          when message_candidate_count>1
            or source_candidate_count>1
            or (message_candidate_count=1 and source_candidate_count=1 and source_candidate_id<>message_candidate_id)
            then 'blocked'
          else 'unresolved'
        end readiness_status,
        case
          when message_candidate_count=1
               and source_candidate_count in (0,1)
               and (source_candidate_count=0 or source_candidate_id=message_candidate_id)
            then message_candidate_id
          when message_candidate_count=0 and source_candidate_count=1
            then source_candidate_id
          else null
        end candidate_conversation_id,
        case
          when message_candidate_count=1
               and source_candidate_count in (0,1)
               and (source_candidate_count=0 or source_candidate_id=message_candidate_id)
            then 'source_message'
          when message_candidate_count=0 and source_candidate_count=1
            then 'source_conversation_id'
          else null
        end evidence_type,
        array_remove(array[
          case when message_candidate_count>1 then 'multiple_message_conversations' end,
          case when source_candidate_count>1 then 'multiple_source_conversations' end,
          case when message_candidate_count=1 and source_candidate_count=1
                    and source_candidate_id<>message_candidate_id then 'conflicting_structured_identity' end,
          case when existing_conversation_id is null
                    and message_candidate_count=0 and source_candidate_count=0 then 'no_structured_conversation_match' end
        ]::text[],null) reasons
      from grouped g
    )
    select jsonb_build_object(
      'summary',jsonb_build_object(
        'entities_total',(select count(*) from classified),
        'ready',(select count(*) from classified where readiness_status='ready'),
        'already_linked',(select count(*) from classified where readiness_status='already_linked'),
        'blocked',(select count(*) from classified where readiness_status='blocked'),
        'unresolved',(select count(*) from classified where readiness_status='unresolved'),
        'rfq_ready',(select count(*) from classified where readiness_status='ready' and entity_type='rfq'),
        'offer_ready',(select count(*) from classified where readiness_status='ready' and entity_type='offer'),
        'order_ready',(select count(*) from classified where readiness_status='ready' and entity_type='order')
      ),
      'candidates',coalesce((
        select jsonb_agg(jsonb_build_object(
          'entity_type',entity_type,
          'entity_id',entity_id,
          'candidate_conversation_id',candidate_conversation_id,
          'evidence_type',evidence_type,
          'line_count',line_count,
          'reasons',to_jsonb(reasons)
        ) order by entity_type,entity_id)
        from (
          select * from classified
          where readiness_status='ready'
          limit greatest(1,least(coalesce(p_limit,100),500))
        ) q
      ),'[]'::jsonb),
      'policy',jsonb_build_object(
        'source_message_exact',true,
        'source_conversation_id_exact',true,
        'subject_inference',false,
        'email_domain_inference',false,
        'free_text_inference',false,
        'legacy_thread_similarity',false,
        'bulk_auto_backfill',false
      )
    )
  );
end;
$$;

revoke all on function public.p1_conversation_backfill_readiness(uuid,integer) from public,anon;
grant execute on function public.p1_conversation_backfill_readiness(uuid,integer) to authenticated,service_role;

create or replace function private.apply_conversation_backfill_impl(
  p_organization_id uuid,
  p_entity_type text,
  p_entity_id uuid,
  p_conversation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  actor_id uuid := (select auth.uid());
  existing_conversation uuid;
  readiness jsonb;
  candidate jsonb;
  evidence_type text;
  audit_id bigint;
begin
  if actor_id is null then raise exception 'Authentication required'; end if;
  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;
  if p_entity_type not in ('rfq','offer','order') then
    raise exception 'Unsupported entity type';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'conversation-backfill:'||p_organization_id::text||':'||p_entity_type||':'||p_entity_id::text,0));

  if exists (
    select 1 from public.commercial_conversation_backfills
    where organization_id=p_organization_id
      and entity_type=p_entity_type
      and entity_id=p_entity_id
      and status='applied'
  ) then
    select id,conversation_id into audit_id,existing_conversation
    from public.commercial_conversation_backfills
    where organization_id=p_organization_id
      and entity_type=p_entity_type
      and entity_id=p_entity_id
      and status='applied';

    return jsonb_build_object(
      'status','already_applied',
      'audit_id',audit_id,
      'conversation_id',existing_conversation
    );
  end if;

  if p_entity_type='rfq' then
    select conversation_id into existing_conversation
    from public.rfqs
    where organization_id=p_organization_id and id=p_entity_id;
  elsif p_entity_type='offer' then
    select conversation_id into existing_conversation
    from public.offers
    where organization_id=p_organization_id and id=p_entity_id;
  else
    select conversation_id into existing_conversation
    from public.orders
    where organization_id=p_organization_id and id=p_entity_id;
  end if;

  if existing_conversation is not null then
    if existing_conversation=p_conversation_id then
      return jsonb_build_object('status','already_linked','conversation_id',existing_conversation);
    end if;
    return jsonb_build_object('status','blocked','reason','conflicting_existing_conversation');
  end if;

  readiness := public.p1_conversation_backfill_readiness(p_organization_id,500);

  select x into candidate
  from jsonb_array_elements(readiness->'candidates') x
  where x->>'entity_type'=p_entity_type
    and x->>'entity_id'=p_entity_id::text
    and x->>'candidate_conversation_id'=p_conversation_id::text
  limit 1;

  if candidate is null then
    return jsonb_build_object('status','blocked','reason','candidate_not_ready');
  end if;

  evidence_type := candidate->>'evidence_type';

  if p_entity_type='rfq' then
    update public.rfqs
    set conversation_id=p_conversation_id
    where organization_id=p_organization_id and id=p_entity_id and conversation_id is null;
  elsif p_entity_type='offer' then
    update public.offers
    set conversation_id=p_conversation_id
    where organization_id=p_organization_id and id=p_entity_id and conversation_id is null;
  else
    update public.orders
    set conversation_id=p_conversation_id
    where organization_id=p_organization_id and id=p_entity_id and conversation_id is null;
  end if;

  if not found then
    return jsonb_build_object('status','blocked','reason','entity_not_updated');
  end if;

  insert into public.commercial_conversation_backfills(
    organization_id,entity_type,entity_id,conversation_id,evidence_type,
    status,activated_by,metadata
  ) values (
    p_organization_id,p_entity_type,p_entity_id,p_conversation_id,evidence_type,
    'applied',actor_id,
    jsonb_build_object('phase','PA2.22','execution_mode','single_explicit')
  )
  returning id into audit_id;

  return jsonb_build_object(
    'status','applied',
    'audit_id',audit_id,
    'entity_type',p_entity_type,
    'entity_id',p_entity_id,
    'conversation_id',p_conversation_id,
    'evidence_type',evidence_type,
    'control_phase','PA2.22',
    'execution_mode','single_explicit'
  );
end;
$$;

revoke all on function private.apply_conversation_backfill_impl(uuid,text,uuid,uuid) from public,anon;
grant execute on function private.apply_conversation_backfill_impl(uuid,text,uuid,uuid) to authenticated,service_role;

create or replace function public.p1_apply_conversation_backfill(
  p_organization_id uuid,
  p_entity_type text,
  p_entity_id uuid,
  p_conversation_id uuid
)
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select private.apply_conversation_backfill_impl(
    p_organization_id,p_entity_type,p_entity_id,p_conversation_id
  );
$$;

revoke all on function public.p1_apply_conversation_backfill(uuid,text,uuid,uuid) from public,anon;
grant execute on function public.p1_apply_conversation_backfill(uuid,text,uuid,uuid) to authenticated,service_role;
