create table if not exists public.worker_jobs (
  id uuid primary key default gen_random_uuid(),
  filename text not null,
  extension text not null,
  size_bytes bigint not null,
  storage_path text,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'completed', 'failed')),
  parser_version text not null default 'v3.1',
  input_kind text,
  extraction_count integer not null default 0,
  error text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists worker_jobs_status_created_idx
  on public.worker_jobs (status, created_at desc);

create table if not exists public.worker_staging_observations (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.worker_jobs(id) on delete cascade,
  source_filename text not null,
  source_text text,
  item_role text,
  grade text,
  standard text,
  dimensions jsonb,
  length numeric,
  quantity numeric,
  price numeric,
  currency text,
  availability text,
  confidence numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists worker_staging_observations_job_idx
  on public.worker_staging_observations (job_id);

alter table public.worker_jobs enable row level security;
alter table public.worker_staging_observations enable row level security;

revoke all on public.worker_jobs from anon, authenticated;
revoke all on public.worker_staging_observations from anon, authenticated;

drop policy if exists worker_jobs_no_client_access on public.worker_jobs;
create policy worker_jobs_no_client_access
  on public.worker_jobs
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists worker_staging_no_client_access on public.worker_staging_observations;
create policy worker_staging_no_client_access
  on public.worker_staging_observations
  for all
  to anon, authenticated
  using (false)
  with check (false);
