-- P2.6 — Cross-Thread Relationship Evidence & Conversion Activation.
-- Candidate generation is deterministic and evidence-first. No candidate auto-activates.

create table if not exists public.commercial_relationship_evidence_decisions (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  relationship_type text not null check (relationship_type in ('offer_rfq','order_offer','order_rfq')),
  source_entity_id uuid not null,
  target_entity_id uuid not null,
  source_conversation_id uuid not null references public.conversations(id) on delete restrict,
  target_conversation_id uuid not null references public.conversations(id) on delete restrict,
  company_id uuid not null references public.companies(id) on delete restrict,
  decision text not null check (decision in ('accepted','rejected')),
  evidence_class text not null check (evidence_class in ('strong_review','review')),
  evidence_snapshot jsonb not null,
  note text,
  decided_by uuid not null references auth.users(id) on delete restrict,
  decided_at timestamptz not null default now(),
  unique (organization_id,relationship_type,source_entity_id,target_entity_id)
);

alter table public.commercial_relationship_evidence_decisions enable row level security;

drop policy if exists commercial_relationship_evidence_decisions_select
  on public.commercial_relationship_evidence_decisions;

create policy commercial_relationship_evidence_decisions_select
on public.commercial_relationship_evidence_decisions
for select
to authenticated
using (public.is_organization_member(organization_id,false));

revoke all on table public.commercial_relationship_evidence_decisions from public,anon,authenticated;
grant select on table public.commercial_relationship_evidence_decisions to authenticated;
grant all on table public.commercial_relationship_evidence_decisions to service_role;

create index if not exists commercial_relationship_evidence_decisions_org_idx
  on public.commercial_relationship_evidence_decisions(organization_id,decided_at desc);

create index if not exists commercial_relationship_evidence_decisions_pair_idx
  on public.commercial_relationship_evidence_decisions(
    organization_id,relationship_type,source_entity_id,target_entity_id
  );

alter table public.commercial_relationship_activations
  drop constraint if exists commercial_relationship_activations_evidence_type_check;

alter table public.commercial_relationship_activations
  add constraint commercial_relationship_activations_evidence_type_check
  check (
    evidence_type in (
      'shared_normalized_conversation_exact_product',
      'human_confirmed_cross_thread_evidence'
    )
  );

create or replace function public.p2_cross_thread_candidate_evidence(
  p_organization_id uuid,
  p_relationship_type text,
  p_source_entity_id uuid,
  p_target_entity_id uuid,
  p_window_days integer default 90
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  result jsonb;
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  if p_relationship_type not in ('offer_rfq','order_offer','order_rfq') then
    return null;
  end if;

  if coalesce(p_window_days,0) < 1 or p_window_days > 180 then
    raise exception 'window_days must be between 1 and 180';
  end if;

  with source_entity as (
    select
      'offer'::text entity_kind,
      o.id entity_id,
      o.company_id,
      o.conversation_id,
      o.rfq_id existing_target_id,
      co.name company_name,
      coalesce(ct.started_at,o.offered_at) evidence_start_at,
      coalesce(ct.last_activity_at,o.offered_at) evidence_end_at
    from public.offers o
    join public.conversations c
      on c.organization_id=o.organization_id and c.id=o.conversation_id
    left join public.companies co
      on co.organization_id=o.organization_id and co.id=o.company_id
    left join lateral (
      select min(t.started_at) started_at,max(t.last_activity_at) last_activity_at
      from public.commercial_threads t
      where t.organization_id=o.organization_id
        and t.source_conversation_id::text=c.external_thread_id
    ) ct on true
    where p_relationship_type='offer_rfq'
      and o.organization_id=p_organization_id
      and o.id=p_source_entity_id

    union all

    select
      'order',
      o.id,
      o.company_id,
      o.conversation_id,
      case
        when p_relationship_type='order_offer' then o.offer_id
        else o.rfq_id
      end,
      co.name,
      coalesce(ct.started_at,o.ordered_at),
      coalesce(ct.last_activity_at,o.ordered_at)
    from public.orders o
    join public.conversations c
      on c.organization_id=o.organization_id and c.id=o.conversation_id
    left join public.companies co
      on co.organization_id=o.organization_id and co.id=o.company_id
    left join lateral (
      select min(t.started_at) started_at,max(t.last_activity_at) last_activity_at
      from public.commercial_threads t
      where t.organization_id=o.organization_id
        and t.source_conversation_id::text=c.external_thread_id
    ) ct on true
    where p_relationship_type in ('order_offer','order_rfq')
      and o.organization_id=p_organization_id
      and o.id=p_source_entity_id
  ),
  target_entity as (
    select
      'rfq'::text entity_kind,
      r.id entity_id,
      r.company_id,
      r.conversation_id,
      co.name company_name,
      coalesce(ct.started_at,r.requested_at) evidence_start_at,
      coalesce(ct.last_activity_at,r.requested_at) evidence_end_at
    from public.rfqs r
    join public.conversations c
      on c.organization_id=r.organization_id and c.id=r.conversation_id
    left join public.companies co
      on co.organization_id=r.organization_id and co.id=r.company_id
    left join lateral (
      select min(t.started_at) started_at,max(t.last_activity_at) last_activity_at
      from public.commercial_threads t
      where t.organization_id=r.organization_id
        and t.source_conversation_id::text=c.external_thread_id
    ) ct on true
    where p_relationship_type in ('offer_rfq','order_rfq')
      and r.organization_id=p_organization_id
      and r.id=p_target_entity_id

    union all

    select
      'offer',
      o.id,
      o.company_id,
      o.conversation_id,
      co.name,
      coalesce(ct.started_at,o.offered_at),
      coalesce(ct.last_activity_at,o.offered_at)
    from public.offers o
    join public.conversations c
      on c.organization_id=o.organization_id and c.id=o.conversation_id
    left join public.companies co
      on co.organization_id=o.organization_id and co.id=o.company_id
    left join lateral (
      select min(t.started_at) started_at,max(t.last_activity_at) last_activity_at
      from public.commercial_threads t
      where t.organization_id=o.organization_id
        and t.source_conversation_id::text=c.external_thread_id
    ) ct on true
    where p_relationship_type='order_offer'
      and o.organization_id=p_organization_id
      and o.id=p_target_entity_id
  ),
  source_contact as (
    select
      case
        when count(distinct m.sender_contact_id)=1
          then (min(m.sender_contact_id::text)
                filter(where m.sender_contact_id is not null))::uuid
        else null
      end contact_id
    from source_entity e
    left join public.messages m
      on m.organization_id=p_organization_id
     and m.conversation_id=e.conversation_id
     and coalesce(m.direction,'inbound')<>'outbound'
  ),
  target_contact as (
    select
      case
        when count(distinct m.sender_contact_id)=1
          then (min(m.sender_contact_id::text)
                filter(where m.sender_contact_id is not null))::uuid
        else null
      end contact_id
    from target_entity e
    left join public.messages m
      on m.organization_id=p_organization_id
     and m.conversation_id=e.conversation_id
     and coalesce(m.direction,'inbound')<>'outbound'
  ),
  source_lines as (
    select
      rl.id line_id,
      rl.canonical_product_key,
      concat_ws('|',
        split_part(rl.canonical_product_key,'|',1),
        split_part(rl.canonical_product_key,'|',2),
        split_part(rl.canonical_product_key,'|',6),
        split_part(rl.canonical_product_key,'|',7)
      ) geometry_key,
      rl.raw_spec_text
    from public.rfq_lines rl
    where (select entity_kind from source_entity)='rfq'
      and rl.organization_id=p_organization_id
      and rl.rfq_id=p_source_entity_id
      and rl.canonical_product_key is not null

    union all

    select
      ol.id,
      ol.canonical_product_key,
      concat_ws('|',
        split_part(ol.canonical_product_key,'|',1),
        split_part(ol.canonical_product_key,'|',2),
        split_part(ol.canonical_product_key,'|',6),
        split_part(ol.canonical_product_key,'|',7)
      ),
      ol.raw_spec_text
    from public.offer_lines ol
    where (select entity_kind from source_entity)='offer'
      and ol.organization_id=p_organization_id
      and ol.offer_id=p_source_entity_id
      and ol.canonical_product_key is not null

    union all

    select
      ol.id,
      ol.canonical_product_key,
      concat_ws('|',
        split_part(ol.canonical_product_key,'|',1),
        split_part(ol.canonical_product_key,'|',2),
        split_part(ol.canonical_product_key,'|',6),
        split_part(ol.canonical_product_key,'|',7)
      ),
      ol.raw_spec_text
    from public.order_lines ol
    where (select entity_kind from source_entity)='order'
      and ol.organization_id=p_organization_id
      and ol.order_id=p_source_entity_id
      and ol.canonical_product_key is not null
  ),
  target_lines as (
    select
      rl.id line_id,
      rl.canonical_product_key,
      concat_ws('|',
        split_part(rl.canonical_product_key,'|',1),
        split_part(rl.canonical_product_key,'|',2),
        split_part(rl.canonical_product_key,'|',6),
        split_part(rl.canonical_product_key,'|',7)
      ) geometry_key,
      rl.raw_spec_text
    from public.rfq_lines rl
    where (select entity_kind from target_entity)='rfq'
      and rl.organization_id=p_organization_id
      and rl.rfq_id=p_target_entity_id
      and rl.canonical_product_key is not null

    union all

    select
      ol.id,
      ol.canonical_product_key,
      concat_ws('|',
        split_part(ol.canonical_product_key,'|',1),
        split_part(ol.canonical_product_key,'|',2),
        split_part(ol.canonical_product_key,'|',6),
        split_part(ol.canonical_product_key,'|',7)
      ),
      ol.raw_spec_text
    from public.offer_lines ol
    where (select entity_kind from target_entity)='offer'
      and ol.organization_id=p_organization_id
      and ol.offer_id=p_target_entity_id
      and ol.canonical_product_key is not null

    union all

    select
      ol.id,
      ol.canonical_product_key,
      concat_ws('|',
        split_part(ol.canonical_product_key,'|',1),
        split_part(ol.canonical_product_key,'|',2),
        split_part(ol.canonical_product_key,'|',6),
        split_part(ol.canonical_product_key,'|',7)
      ),
      ol.raw_spec_text
    from public.order_lines ol
    where (select entity_kind from target_entity)='order'
      and ol.organization_id=p_organization_id
      and ol.order_id=p_target_entity_id
      and ol.canonical_product_key is not null
  ),
  source_exact as (
    select canonical_product_key,count(*)::int n
    from source_lines group by canonical_product_key
  ),
  target_exact as (
    select canonical_product_key,count(*)::int n
    from target_lines group by canonical_product_key
  ),
  source_geometry as (
    select geometry_key,count(*)::int n
    from source_lines group by geometry_key
  ),
  target_geometry as (
    select geometry_key,count(*)::int n
    from target_lines group by geometry_key
  ),
  overlap as (
    select
      coalesce((
        select sum(least(s.n,t.n))::int
        from source_exact s
        join target_exact t using(canonical_product_key)
      ),0) exact_product_overlap_count,
      coalesce((
        select sum(least(s.n,t.n))::int
        from source_geometry s
        join target_geometry t using(geometry_key)
      ),0) geometry_overlap_count
  ),
  line_evidence as (
    select coalesce(jsonb_agg(e.obj order by e.canonical_match desc,e.source_line_id,e.target_line_id),'[]'::jsonb) value
    from (
      select
        s.line_id source_line_id,
        t.line_id target_line_id,
        (s.canonical_product_key=t.canonical_product_key) canonical_match,
        jsonb_build_object(
          'source_line_id',s.line_id,
          'target_line_id',t.line_id,
          'source_canonical_product_key',s.canonical_product_key,
          'target_canonical_product_key',t.canonical_product_key,
          'geometry_key',s.geometry_key,
          'canonical_match',s.canonical_product_key=t.canonical_product_key,
          'source_text',s.raw_spec_text,
          'target_text',t.raw_spec_text
        ) obj
      from source_lines s
      join target_lines t using(geometry_key)
      order by (s.canonical_product_key=t.canonical_product_key) desc,s.line_id,t.line_id
      limit 20
    ) e
  ),
  candidate as (
    select
      s.entity_kind source_kind,
      t.entity_kind target_kind,
      s.entity_id source_entity_id,
      t.entity_id target_entity_id,
      s.company_id,
      coalesce(s.company_name,t.company_name) company_name,
      s.conversation_id source_conversation_id,
      t.conversation_id target_conversation_id,
      s.evidence_start_at source_evidence_at,
      t.evidence_end_at target_evidence_at,
      extract(epoch from (s.evidence_start_at-t.evidence_end_at))/3600.0 gap_hours,
      sc.contact_id source_contact_id,
      tc.contact_id target_contact_id,
      sc.contact_id is not null
        and tc.contact_id is not null
        and sc.contact_id=tc.contact_id shared_contact,
      o.exact_product_overlap_count,
      o.geometry_overlap_count,
      le.value line_evidence
    from source_entity s
    cross join target_entity t
    cross join source_contact sc
    cross join target_contact tc
    cross join overlap o
    cross join line_evidence le
    where s.existing_target_id is null
      and s.conversation_id is not null
      and t.conversation_id is not null
      and s.conversation_id<>t.conversation_id
      and s.company_id is not null
      and s.company_id=t.company_id
      and exists (
        select 1
        from public.commercial_company_identity_verifications v
        where v.organization_id=p_organization_id
          and v.company_id=s.company_id
      )
      and s.evidence_start_at is not null
      and t.evidence_end_at is not null
      and s.evidence_start_at>=t.evidence_end_at
      and s.evidence_start_at<=t.evidence_end_at+make_interval(days=>p_window_days)
      and (o.exact_product_overlap_count>0 or o.geometry_overlap_count>0)
  )
  select jsonb_build_object(
    'relationship_type',p_relationship_type,
    'source_kind',source_kind,
    'target_kind',target_kind,
    'source_entity_id',source_entity_id,
    'target_entity_id',target_entity_id,
    'company_id',company_id,
    'company_name',company_name,
    'source_conversation_id',source_conversation_id,
    'target_conversation_id',target_conversation_id,
    'source_evidence_at',source_evidence_at,
    'target_evidence_at',target_evidence_at,
    'gap_hours',round(gap_hours::numeric,2),
    'gap_days',round((gap_hours/24.0)::numeric,2),
    'source_contact_id',source_contact_id,
    'target_contact_id',target_contact_id,
    'shared_contact',shared_contact,
    'exact_product_overlap_count',exact_product_overlap_count,
    'geometry_overlap_count',geometry_overlap_count,
    'evidence_class',case
      when shared_contact and gap_hours<=720 and geometry_overlap_count>0
        then 'strong_review'
      else 'review'
    end,
    'reason_codes',to_jsonb(array_remove(array[
      'same_verified_company',
      'distinct_conversation',
      'chronological_window',
      case when shared_contact then 'same_exact_contact' end,
      case when exact_product_overlap_count>0 then 'exact_canonical_product_overlap' end,
      case when geometry_overlap_count>0 then 'exact_geometry_overlap' end
    ],null)),
    'line_evidence',line_evidence
  )
  into result
  from candidate;

  return result;
end;
$$;

revoke all on function public.p2_cross_thread_candidate_evidence(uuid,text,uuid,uuid,integer)
  from public,anon;
grant execute on function public.p2_cross_thread_candidate_evidence(uuid,text,uuid,uuid,integer)
  to authenticated,service_role;

create or replace function public.p2_cross_thread_relationship_evidence(
  p_organization_id uuid,
  p_window_days integer default 90,
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  result jsonb;
begin
  if (select auth.uid()) is null
     or not public.is_organization_member(p_organization_id,false) then
    raise exception 'organization access denied' using errcode='42501';
  end if;

  if coalesce(p_window_days,0) < 1 or p_window_days > 180 then
    raise exception 'window_days must be between 1 and 180';
  end if;

  with verified_companies as (
    select distinct company_id
    from public.commercial_company_identity_verifications
    where organization_id=p_organization_id
  ),
  raw_pairs as (
    select
      'offer_rfq'::text relationship_type,
      o.id source_entity_id,
      r.id target_entity_id
    from public.offers o
    join public.rfqs r
      on r.organization_id=o.organization_id
     and r.company_id=o.company_id
     and r.conversation_id is distinct from o.conversation_id
    where o.organization_id=p_organization_id
      and o.rfq_id is null
      and o.company_id in (select company_id from verified_companies)

    union all

    select
      'order_offer',
      o.id,
      f.id
    from public.orders o
    join public.offers f
      on f.organization_id=o.organization_id
     and f.company_id=o.company_id
     and f.conversation_id is distinct from o.conversation_id
    where o.organization_id=p_organization_id
      and o.offer_id is null
      and o.company_id in (select company_id from verified_companies)

    union all

    select
      'order_rfq',
      o.id,
      r.id
    from public.orders o
    join public.rfqs r
      on r.organization_id=o.organization_id
     and r.company_id=o.company_id
     and r.conversation_id is distinct from o.conversation_id
    where o.organization_id=p_organization_id
      and o.rfq_id is null
      and o.company_id in (select company_id from verified_companies)
  ),
  undecided_pairs as (
    select p.*
    from raw_pairs p
    where not exists (
      select 1
      from public.commercial_relationship_evidence_decisions d
      where d.organization_id=p_organization_id
        and d.relationship_type=p.relationship_type
        and d.source_entity_id=p.source_entity_id
        and d.target_entity_id=p.target_entity_id
    )
      and not exists (
        select 1
        from public.commercial_relationship_activations a
        where a.organization_id=p_organization_id
          and a.relationship_type=p.relationship_type
          and a.source_entity_id=p.source_entity_id
          and a.target_entity_id=p.target_entity_id
          and a.status='applied'
      )
  ),
  evidence as (
    select e.payload
    from undecided_pairs p
    cross join lateral (
      select public.p2_cross_thread_candidate_evidence(
        p_organization_id,
        p.relationship_type,
        p.source_entity_id,
        p.target_entity_id,
        p_window_days
      ) payload
    ) e
    where e.payload is not null
  ),
  ordered as (
    select payload
    from evidence
    order by
      case payload->>'evidence_class'
        when 'strong_review' then 0
        else 1
      end,
      (payload->>'gap_hours')::numeric,
      payload->>'relationship_type',
      payload->>'source_entity_id'
  ),
  paged as (
    select payload
    from ordered
    limit greatest(1,least(coalesce(p_limit,100),500))
    offset greatest(0,coalesce(p_offset,0))
  ),
  decision_summary as (
    select
      count(*) filter(where decision='accepted')::int accepted,
      count(*) filter(where decision='rejected')::int rejected
    from public.commercial_relationship_evidence_decisions
    where organization_id=p_organization_id
  )
  select jsonb_build_object(
    'summary',jsonb_build_object(
      'pending_total',(select count(*) from evidence),
      'strong_review_count',(select count(*) from evidence where payload->>'evidence_class'='strong_review'),
      'review_count',(select count(*) from evidence where payload->>'evidence_class'='review'),
      'offer_rfq_pending',(select count(*) from evidence where payload->>'relationship_type'='offer_rfq'),
      'order_offer_pending',(select count(*) from evidence where payload->>'relationship_type'='order_offer'),
      'order_rfq_pending',(select count(*) from evidence where payload->>'relationship_type'='order_rfq'),
      'accepted_total',(select accepted from decision_summary),
      'rejected_total',(select rejected from decision_summary)
    ),
    'candidates',coalesce(
      (select jsonb_agg(payload) from paged),
      '[]'::jsonb
    ),
    'policy',jsonb_build_object(
      'window_days',p_window_days,
      'verified_same_company_required',true,
      'distinct_conversation_required',true,
      'chronological_order_required',true,
      'canonical_or_exact_geometry_overlap_required',true,
      'strong_review_max_days',30,
      'human_decision_required',true,
      'automatic_activation',false,
      'email_domain_inference',false,
      'filename_inference',false,
      'subject_similarity',false,
      'embedding_similarity',false,
      'fuzzy_dimension_tolerance',false,
      'geometry_only_line_fk',false
    )
  )
  into result;

  return result;
end;
$$;

revoke all on function public.p2_cross_thread_relationship_evidence(uuid,integer,integer,integer)
  from public,anon;
grant execute on function public.p2_cross_thread_relationship_evidence(uuid,integer,integer,integer)
  to authenticated,service_role;

create or replace function private.p2_decide_cross_thread_relationship_impl(
  p_organization_id uuid,
  p_relationship_type text,
  p_source_entity_id uuid,
  p_target_entity_id uuid,
  p_decision text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := (select auth.uid());
  evidence jsonb;
  decision_id bigint;
  activation_id bigint;
  existing_target uuid;
  linked_line_count integer := 0;
  outcome_result jsonb;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_organization_member(p_organization_id,true) then
    raise exception 'Active organization write membership required';
  end if;

  if p_relationship_type not in ('offer_rfq','order_offer','order_rfq') then
    raise exception 'Unsupported relationship type';
  end if;

  if p_decision not in ('accepted','rejected') then
    raise exception 'Decision must be accepted or rejected';
  end if;

  if exists (
    select 1
    from public.commercial_relationship_evidence_decisions d
    where d.organization_id=p_organization_id
      and d.relationship_type=p_relationship_type
      and d.source_entity_id=p_source_entity_id
      and d.target_entity_id=p_target_entity_id
  ) then
    return jsonb_build_object('status','already_decided');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(
    'p2.6:'||p_organization_id::text||':'||p_relationship_type||':'||p_source_entity_id::text,0
  ));

  if p_relationship_type='offer_rfq' then
    select rfq_id
    into existing_target
    from public.offers
    where organization_id=p_organization_id and id=p_source_entity_id
    for update;
  elsif p_relationship_type='order_offer' then
    select offer_id
    into existing_target
    from public.orders
    where organization_id=p_organization_id and id=p_source_entity_id
    for update;
  else
    select rfq_id
    into existing_target
    from public.orders
    where organization_id=p_organization_id and id=p_source_entity_id
    for update;
  end if;

  if existing_target is not null then
    return jsonb_build_object(
      'status','blocked',
      'reason','conflicting_or_existing_relationship',
      'existing_target_id',existing_target
    );
  end if;

  evidence := public.p2_cross_thread_candidate_evidence(
    p_organization_id,
    p_relationship_type,
    p_source_entity_id,
    p_target_entity_id,
    90
  );

  if evidence is null then
    return jsonb_build_object(
      'status','blocked',
      'reason','candidate_no_longer_eligible'
    );
  end if;

  insert into public.commercial_relationship_evidence_decisions(
    organization_id,
    relationship_type,
    source_entity_id,
    target_entity_id,
    source_conversation_id,
    target_conversation_id,
    company_id,
    decision,
    evidence_class,
    evidence_snapshot,
    note,
    decided_by
  ) values (
    p_organization_id,
    p_relationship_type,
    p_source_entity_id,
    p_target_entity_id,
    (evidence->>'source_conversation_id')::uuid,
    (evidence->>'target_conversation_id')::uuid,
    (evidence->>'company_id')::uuid,
    p_decision,
    evidence->>'evidence_class',
    evidence,
    nullif(btrim(coalesce(p_note,'')),''),
    actor_id
  )
  returning id into decision_id;

  if p_decision='rejected' then
    return jsonb_build_object(
      'status','rejected',
      'decision_id',decision_id,
      'relationship_type',p_relationship_type,
      'source_entity_id',p_source_entity_id,
      'target_entity_id',p_target_entity_id
    );
  end if;

  if p_relationship_type='offer_rfq' then
    update public.offers
    set rfq_id=p_target_entity_id
    where organization_id=p_organization_id
      and id=p_source_entity_id
      and rfq_id is null;

    update public.offer_lines ol
    set rfq_line_id=(
      select rl.id
      from public.rfq_lines rl
      where rl.organization_id=p_organization_id
        and rl.rfq_id=p_target_entity_id
        and rl.canonical_product_key=ol.canonical_product_key
      limit 1
    )
    where ol.organization_id=p_organization_id
      and ol.offer_id=p_source_entity_id
      and ol.canonical_product_key is not null
      and (
        select count(*)
        from public.rfq_lines rl
        where rl.organization_id=p_organization_id
          and rl.rfq_id=p_target_entity_id
          and rl.canonical_product_key=ol.canonical_product_key
      )=1;
    get diagnostics linked_line_count=row_count;

  elsif p_relationship_type='order_offer' then
    update public.orders
    set offer_id=p_target_entity_id
    where organization_id=p_organization_id
      and id=p_source_entity_id
      and offer_id is null;

    update public.order_lines ol
    set offer_line_id=(
      select fl.id
      from public.offer_lines fl
      where fl.organization_id=p_organization_id
        and fl.offer_id=p_target_entity_id
        and fl.canonical_product_key=ol.canonical_product_key
      limit 1
    )
    where ol.organization_id=p_organization_id
      and ol.order_id=p_source_entity_id
      and ol.canonical_product_key is not null
      and (
        select count(*)
        from public.offer_lines fl
        where fl.organization_id=p_organization_id
          and fl.offer_id=p_target_entity_id
          and fl.canonical_product_key=ol.canonical_product_key
      )=1;
    get diagnostics linked_line_count=row_count;

  else
    update public.orders
    set rfq_id=p_target_entity_id
    where organization_id=p_organization_id
      and id=p_source_entity_id
      and rfq_id is null;
  end if;

  insert into public.commercial_relationship_activations(
    organization_id,
    relationship_type,
    source_entity_id,
    target_entity_id,
    evidence_type,
    status,
    activated_by,
    metadata
  ) values (
    p_organization_id,
    p_relationship_type,
    p_source_entity_id,
    p_target_entity_id,
    'human_confirmed_cross_thread_evidence',
    'applied',
    actor_id,
    jsonb_build_object(
      'phase','P2.6',
      'decision_id',decision_id,
      'evidence_class',evidence->>'evidence_class',
      'gap_hours',evidence->'gap_hours',
      'shared_contact',evidence->'shared_contact',
      'exact_product_overlap_count',evidence->'exact_product_overlap_count',
      'geometry_overlap_count',evidence->'geometry_overlap_count',
      'linked_line_count',linked_line_count,
      'execution_mode','single_human_confirmed_cross_thread'
    )
  )
  returning id into activation_id;

  outcome_result := private.p2_reconcile_commercial_outcome_attribution_impl(
    p_organization_id
  );

  return jsonb_build_object(
    'status','applied',
    'decision_id',decision_id,
    'activation_id',activation_id,
    'relationship_type',p_relationship_type,
    'source_entity_id',p_source_entity_id,
    'target_entity_id',p_target_entity_id,
    'linked_line_count',linked_line_count,
    'evidence_class',evidence->>'evidence_class',
    'outcome_reconciliation',outcome_result
  );
end;
$$;

revoke execute on function private.p2_decide_cross_thread_relationship_impl(
  uuid,text,uuid,uuid,text,text
) from public,anon,authenticated;
grant execute on function private.p2_decide_cross_thread_relationship_impl(
  uuid,text,uuid,uuid,text,text
) to service_role;

create or replace function public.p2_decide_cross_thread_relationship(
  p_organization_id uuid,
  p_relationship_type text,
  p_source_entity_id uuid,
  p_target_entity_id uuid,
  p_decision text,
  p_note text default null
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.p2_decide_cross_thread_relationship_impl(
    p_organization_id,
    p_relationship_type,
    p_source_entity_id,
    p_target_entity_id,
    p_decision,
    p_note
  );
$$;

revoke all on function public.p2_decide_cross_thread_relationship(
  uuid,text,uuid,uuid,text,text
) from public,anon;
grant execute on function public.p2_decide_cross_thread_relationship(
  uuid,text,uuid,uuid,text,text
) to authenticated,service_role;

comment on table public.commercial_relationship_evidence_decisions is
  'P2.6 immutable human decisions over cross-thread RFQ/Offer/Order relationship evidence.';

comment on function public.p2_cross_thread_relationship_evidence(uuid,integer,integer,integer) is
  'P2.6 evidence-first cross-thread relationship candidates. Candidate presence never implies automatic activation.';

comment on function public.p2_decide_cross_thread_relationship(uuid,text,uuid,uuid,text,text) is
  'P2.6 explicit human accept/reject decision. Accepted candidates are revalidated before one controlled relationship mutation.';
