create table public.pilot_usage_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (event_name in ('search_completed','product_viewed','company_viewed','price_history_viewed','evidence_opened','review_viewed','correction_completed','upload_completed')),
  entity_type text,
  entity_id text,
  outcome text not null default 'success' check (outcome in ('success','empty','error')),
  result_count integer check (result_count is null or result_count >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index pilot_usage_events_org_time_idx on public.pilot_usage_events(organization_id, occurred_at desc);
create index pilot_usage_events_actor_time_idx on public.pilot_usage_events(actor_user_id, occurred_at desc);
create index pilot_usage_events_name_time_idx on public.pilot_usage_events(event_name, occurred_at desc);
alter table public.pilot_usage_events enable row level security;
revoke all on table public.pilot_usage_events from public, anon, authenticated;
grant select,insert,update,delete on table public.pilot_usage_events to service_role, postgres;
grant usage,select on sequence public.pilot_usage_events_id_seq to service_role, postgres;

create or replace function public.p1_record_pilot_usage_event(p_organization_id uuid,p_event_name text,p_entity_type text default null,p_entity_id text default null,p_outcome text default 'success',p_result_count integer default null,p_duration_ms integer default null,p_metadata jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path to '' as $$
declare v_actor uuid:=auth.uid(); v_id bigint; v_safe_metadata jsonb:='{}'::jsonb;
begin
 if v_actor is null then raise exception using errcode='28000',message='authentication required'; end if;
 if p_organization_id is null or not public.is_organization_member(p_organization_id,true) then raise exception using errcode='42501',message='active tenant membership required'; end if;
 if p_event_name not in ('search_completed','product_viewed','company_viewed','price_history_viewed','evidence_opened','review_viewed','correction_completed','upload_completed') then raise exception using errcode='22023',message='unsupported pilot event'; end if;
 if p_outcome not in ('success','empty','error') then raise exception using errcode='22023',message='invalid outcome'; end if;
 v_safe_metadata:=jsonb_strip_nulls(jsonb_build_object('source',p_metadata->>'source','surface',p_metadata->>'surface','format',p_metadata->>'format'));
 insert into public.pilot_usage_events(organization_id,actor_user_id,event_name,entity_type,entity_id,outcome,result_count,duration_ms,metadata)
 values(p_organization_id,v_actor,p_event_name,nullif(left(coalesce(p_entity_type,''),40),''),nullif(left(coalesce(p_entity_id,''),120),''),p_outcome,p_result_count,p_duration_ms,v_safe_metadata)
 returning id into v_id; return v_id;
end $$;
revoke all on function public.p1_record_pilot_usage_event(uuid,text,text,text,text,integer,integer,jsonb) from public,anon;
grant execute on function public.p1_record_pilot_usage_event(uuid,text,text,text,text,integer,integer,jsonb) to authenticated,service_role,postgres;

create or replace function public.p1_pilot_usage_summary(p_organization_id uuid,p_since timestamptz default (now()-interval '30 days'))
returns jsonb language plpgsql stable security definer set search_path to '' as $$
declare v_actor uuid:=auth.uid(); v_result jsonb;
begin
 if v_actor is null then raise exception using errcode='28000',message='authentication required'; end if;
 if p_organization_id is null or not public.is_organization_member(p_organization_id,true) then raise exception using errcode='42501',message='active tenant membership required'; end if;
 select jsonb_build_object('contract','PA2.34-v1','since',p_since,'generated_at',now(),'weekly_active_users',count(distinct actor_user_id) filter(where occurred_at>=now()-interval '7 days'),'active_users',count(distinct actor_user_id),'searches',count(*) filter(where event_name='search_completed'),'search_success_rate',case when count(*) filter(where event_name='search_completed')=0 then null else round((count(*) filter(where event_name='search_completed' and outcome='success'))::numeric/nullif(count(*) filter(where event_name='search_completed'),0),4) end,'product_views',count(*) filter(where event_name='product_viewed'),'company_views',count(*) filter(where event_name='company_viewed'),'price_history_views',count(*) filter(where event_name='price_history_viewed'),'evidence_opens',count(*) filter(where event_name='evidence_opened'),'review_views',count(*) filter(where event_name='review_viewed'),'corrections_completed',count(*) filter(where event_name='correction_completed'),'uploads_completed',count(*) filter(where event_name='upload_completed'),'event_count',count(*))
 into v_result from public.pilot_usage_events where organization_id=p_organization_id and occurred_at>=p_since;
 return v_result;
end $$;
revoke all on function public.p1_pilot_usage_summary(uuid,timestamptz) from public,anon;
grant execute on function public.p1_pilot_usage_summary(uuid,timestamptz) to authenticated,service_role,postgres;